"""The entity and report registry -- GENERATED, do not edit by hand.

Generated by ``tools/generate_entities.py`` from the documentation JSON
vendored in ``refs/docs/``, which is the same data developer.intuit.com
renders. Re-generate after ``scripts/refresh_sources.py``.

Operations come from the documented HTTP routes, not from the XSD -- the
schema describes shape and says nothing about which verbs an endpoint
accepts. Field requirements come from the documented request models,
which is the only source that distinguishes required from optional at
all (every XSD field reports ``minOccurs=0``).
"""

from __future__ import annotations

from enum import StrEnum
from typing import Final, Mapping, NamedTuple

__all__ = [
    "Operation",
    "EntitySpec",
    "ENTITIES",
    "ReportSpec",
    "REPORTS",
    "REPORT_ROUTES",
    "DEFAULT_MINOR_VERSION",
    "entity_names",
    "report_names",
    "report_route",
    "supports",
]

#: The minorversion the documentation currently defaults to.
DEFAULT_MINOR_VERSION: Final[int] = 75


class Operation(StrEnum):
    """An operation the Accounting API documents for an endpoint."""

    CREATE = "CREATE"
    DEFAULT = "DEFAULT"
    DELETE = "DELETE"
    DOWNLOAD = "DOWNLOAD"
    PDF = "PDF"
    QUERY = "QUERY"
    READ = "READ"
    SEND = "SEND"
    UPDATE = "UPDATE"
    UPLOAD = "UPLOAD"


class ReportSpec(NamedTuple):
    """One documented report.

    ``name`` is how the documentation files it; ``route`` is what the URL
    actually takes. They differ for ten of the reports -- calling the
    documented name returns HTTP 400.
    """

    name: str
    route: str
    variants: tuple[str, ...]


class EntitySpec(NamedTuple):
    """One documented entity."""

    name: str
    path: str
    operations: frozenset[Operation]
    required: tuple[str, ...]
    required_for_update: tuple[str, ...]
    conditionally_required: tuple[str, ...]
    #: Fields QuickBooks will accept in a WHERE clause. Filtering by
    #: anything else is rejected with an HTTP 400 that does not say why.
    filterable: tuple[str, ...]
    #: Fields QuickBooks will accept in ORDER BY. Notably excludes
    #: AcctNum, so the chart of accounts cannot be sorted by number.
    sortable: tuple[str, ...]


#: Every entity the Accounting API documents, keyed by its API name.
ENTITIES: Final[Mapping[str, EntitySpec]] = {
    "Account": EntitySpec(
        name="Account",
        path="account",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=("AcctNum",),
        filterable=(
            "AccountSubType",
            "AccountType",
            "Active",
            "Classification",
            "CurrentBalance",
            "CurrentBalanceWithSubAccounts",
            "Description",
            "FullyQualifiedName",
            "Id",
            "Name",
            "ParentRef",
            "SubAccount",
        ),
        sortable=(
            "CurrentBalance",
            "CurrentBalanceWithSubAccounts",
            "Description",
            "FullyQualifiedName",
            "Name",
            "ParentRef",
            "SubAccount",
        ),
    ),
    "Attachable": EntitySpec(
        name="Attachable",
        path="attachable",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.DOWNLOAD,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
                Operation.UPLOAD,
            }
        ),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "FileName",
            "Note",
        ),
        filterable=(
            "Category",
            "ContentType",
            "FileName",
            "Id",
            "Lat",
            "Long",
            "Note",
            "PlaceName",
            "Size",
            "Tag",
            "ThumbnailTempDownloadUri",
        ),
        sortable=(
            "Category",
            "ContentType",
            "FileName",
            "Lat",
            "Long",
            "Note",
            "PlaceName",
            "Size",
            "Tag",
            "ThumbnailTempDownloadUri",
        ),
    ),
    "Bill": EntitySpec(
        name="Bill",
        path="bill",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "VendorRef",
            "Line",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "GlobalTaxCalculation",
        ),
        filterable=(
            "APAccountRef",
            "Balance",
            "DocNumber",
            "DueDate",
            "Id",
            "SalesTermRef",
            "TotalAmt",
            "TxnDate",
            "VendorRef",
        ),
        sortable=(
            "APAccountRef",
            "DocNumber",
            "DueDate",
            "SalesTermRef",
            "TotalAmt",
            "TxnDate",
            "VendorRef",
        ),
    ),
    "BillPayment": EntitySpec(
        name="BillPayment",
        path="billpayment",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "VendorRef",
            "Line",
            "TotalAmt",
            "PayType",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=("CurrencyRef",),
        filterable=(
            "APAccountRef",
            "CheckPayment",
            "CreditCardPayment",
            "DocNumber",
            "Id",
            "TotalAmt",
            "TxnDate",
            "VendorRef",
        ),
        sortable=(
            "APAccountRef",
            "CheckPayment",
            "CreditCardPayment",
            "DocNumber",
            "TotalAmt",
            "TxnDate",
            "VendorRef",
        ),
    ),
    "Budget": EntitySpec(
        name="Budget",
        path="budget",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "EndDate",
            "StartDate",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Active",
            "BudgetType",
            "Id",
            "Name",
        ),
        sortable=(
            "BudgetType",
            "Name",
        ),
    ),
    "ChangeOrder": EntitySpec(
        name="ChangeOrder",
        path="changeorder",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "LinkedTxn",
            "Line",
            "ProjectRef",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=("BillEmail",),
        filterable=(
            "CustomerRef",
            "DocNumber",
            "Id",
            "ProjectRef",
            "TxnDate",
        ),
        sortable=(
            "DocNumber",
            "TxnDate",
        ),
    ),
    "Class": EntitySpec(
        name="Class",
        path="class",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=("ParentRef",),
        filterable=(
            "Active",
            "FullyQualifiedName",
            "Id",
            "MetaData",
        ),
        sortable=(
            "Active",
            "FullyQualifiedName",
            "MetaData",
        ),
    ),
    "CompanyCurrency": EntitySpec(
        name="CompanyCurrency",
        path="companycurrency",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Code",),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Active",
            "Id",
            "MetaData",
        ),
        sortable=(
            "Active",
            "MetaData",
        ),
    ),
    "CompanyInfo": EntitySpec(
        name="CompanyInfo",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ, Operation.UPDATE}),
        required=(),
        required_for_update=(
            "SyncToken",
            "CompanyName",
            "CompanyAddr",
        ),
        conditionally_required=(),
        filterable=("Id",),
        sortable=(),
    ),
    "CreditCardPayment": EntitySpec(
        name="CreditCardPayment",
        path="creditcardpayment",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "CreditCardAccountRef",
            "Amount",
            "BankAccountRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Id",
            "TxnDate",
            "VendorRef",
        ),
        sortable=("TxnDate",),
    ),
    "CreditMemo": EntitySpec(
        name="CreditMemo",
        path="creditmemo",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "Line",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "GlobalTaxCalculation",
            "ProjectRef",
            "BillEmail",
        ),
        filterable=(
            "Balance",
            "CustomerRef",
            "DocNumber",
            "Id",
            "ProjectRef",
            "SalesTermRef",
            "TxnDate",
        ),
        sortable=(
            "Balance",
            "DocNumber",
            "TxnDate",
        ),
    ),
    "Customer": EntitySpec(
        name="Customer",
        path="customer",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "DisplayName",
            "Title",
            "GivenName",
            "MiddleName",
            "Suffix",
            "FamilyName",
        ),
        filterable=(
            "Active",
            "Balance",
            "CompanyName",
            "DisplayName",
            "FamilyName",
            "FullyQualifiedName",
            "GivenName",
            "Id",
            "MiddleName",
            "PrimaryEmailAddr",
            "PrintOnCheckName",
        ),
        sortable=(
            "Active",
            "Balance",
            "BalanceWithJobs",
            "CompanyName",
            "DisplayName",
            "FamilyName",
            "FullyQualifiedName",
            "GivenName",
            "MiddleName",
            "PrintOnCheckName",
        ),
    ),
    "CustomerType": EntitySpec(
        name="CustomerType",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ}),
        required=(),
        required_for_update=(
            "SyncToken",
            "Name",
        ),
        conditionally_required=(),
        filterable=(
            "Active",
            "Id",
            "MetaData",
        ),
        sortable=(
            "Active",
            "MetaData",
        ),
    ),
    "Department": EntitySpec(
        name="Department",
        path="department",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=("ParentRef",),
        filterable=(
            "Active",
            "FullyQualifiedName",
            "Id",
            "MetaData",
        ),
        sortable=(
            "Active",
            "FullyQualifiedName",
            "MetaData",
            "SubDepartment",
        ),
    ),
    "Deposit": EntitySpec(
        name="Deposit",
        path="deposit",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "DepositToAccountRef",
            "Line",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "GlobalTaxCalculation",
            "CurrencyRef",
        ),
        filterable=(
            "Id",
            "TxnDate",
        ),
        sortable=("TxnDate",),
    ),
    "Employee": EntitySpec(
        name="Employee",
        path="employee",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=("PrimaryAddr",),
        filterable=(
            "Active",
            "DisplayName",
            "FamilyName",
            "GivenName",
            "Id",
            "MiddleName",
            "PrintOnCheckName",
            "Suffix",
        ),
        sortable=(
            "DisplayName",
            "FamilyName",
            "GivenName",
            "MiddleName",
            "PrintOnCheckName",
            "Suffix",
        ),
    ),
    "Entitlements": EntitySpec(
        name="Entitlements",
        path="entitlements",
        operations=frozenset({Operation.READ}),
        required=(),
        required_for_update=(),
        conditionally_required=(),
        filterable=(),
        sortable=(),
    ),
    "Estimate": EntitySpec(
        name="Estimate",
        path="estimate",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=("CustomerRef",),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "ShipFromAddr",
            "CurrencyRef",
            "GlobalTaxCalculation",
            "ProjectRef",
            "BillEmail",
        ),
        filterable=(
            "CustomerRef",
            "DocNumber",
            "DueDate",
            "Id",
            "ProjectRef",
            "TxnDate",
        ),
        sortable=(
            "DocNumber",
            "DueDate",
            "TxnDate",
        ),
    ),
    "Exchangerate": EntitySpec(
        name="Exchangerate",
        path="exchangerate",
        operations=frozenset({Operation.QUERY, Operation.UPDATE}),
        required=(),
        required_for_update=(
            "SyncToken",
            "AsOfDate",
            "SourceCurrencyCode",
            "Rate",
        ),
        conditionally_required=(),
        filterable=(
            "AsOfDate",
            "MetaData",
            "SourceCurrencyCode",
        ),
        sortable=("MetaData",),
    ),
    "InventoryAdjustment": EntitySpec(
        name="InventoryAdjustment",
        path="inventoryadjustment",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "TxnDate",
            "Line",
            "AdjustAccountRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=("Id",),
        sortable=(),
    ),
    "Invoice": EntitySpec(
        name="Invoice",
        path="invoice",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "Line",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "ShipFromAddr",
            "CurrencyRef",
            "GlobalTaxCalculation",
            "DocNumber",
            "ProjectRef",
            "BillEmail",
        ),
        filterable=(
            "Balance",
            "CustomerRef",
            "DocNumber",
            "DueDate",
            "Id",
            "ProjectRef",
            "SalesTermRef",
            "TxnDate",
        ),
        sortable=(
            "Balance",
            "DocNumber",
            "DueDate",
            "TxnDate",
        ),
    ),
    "Item": EntitySpec(
        name="Item",
        path="item",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "InvStartDate",
            "Type",
            "QtyOnHand",
            "AssetAccountRef",
        ),
        filterable=(
            "Active",
            "FullyQualifiedName",
            "Id",
            "Name",
            "Sku",
            "Type",
        ),
        sortable=(
            "Name",
            "Type",
            "UnitPrice",
        ),
    ),
    "JournalEntry": EntitySpec(
        name="JournalEntry",
        path="journalentry",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Line",),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "GlobalTaxCalculation",
        ),
        filterable=(
            "DocNumber",
            "Id",
            "TxnDate",
        ),
        sortable=(
            "DocNumber",
            "TxnDate",
        ),
    ),
    "Payment": EntitySpec(
        name="Payment",
        path="payment",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "TotalAmt",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "ProjectRef",
        ),
        filterable=(
            "CustomerRef",
            "Id",
            "PaymentRefNum",
            "ProjectRef",
            "TxnDate",
        ),
        sortable=(
            "PaymentRefNum",
            "TxnDate",
        ),
    ),
    "PaymentMethod": EntitySpec(
        name="PaymentMethod",
        path="paymentmethod",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Active",
            "Id",
        ),
        sortable=("Active",),
    ),
    "Preferences": EntitySpec(
        name="Preferences",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ, Operation.UPDATE}),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(),
        sortable=(),
    ),
    "Purchase": EntitySpec(
        name="Purchase",
        path="purchase",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "Line",
            "PaymentType",
            "AccountRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=("CurrencyRef",),
        filterable=(
            "DocNumber",
            "Id",
            "TxnDate",
        ),
        sortable=(
            "DocNumber",
            "TxnDate",
        ),
    ),
    "PurchaseOrder": EntitySpec(
        name="PurchaseOrder",
        path="purchaseorder",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "APAccountRef",
            "VendorRef",
            "Line",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "GlobalTaxCalculation",
        ),
        filterable=(
            "DocNumber",
            "DueDate",
            "Id",
            "TxnDate",
        ),
        sortable=(
            "DocNumber",
            "DueDate",
            "TxnDate",
        ),
    ),
    "RecurringTransaction": EntitySpec(
        name="RecurringTransaction",
        path="recurringtransaction",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
            }
        ),
        required=("RecurringInfo",),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Id",
            "MetaData",
            "RecurDataRef",
            "Type",
        ),
        sortable=("RecurDataRef",),
    ),
    "RefundReceipt": EntitySpec(
        name="RefundReceipt",
        path="refundreceipt",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "DepositToAccountRef",
            "Line",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "CurrencyRef",
            "PaymentRefNum",
            "GlobalTaxCalculation",
            "ProjectRef",
            "BillEmail",
        ),
        filterable=(
            "Balance",
            "CheckPayment",
            "CreditCardPayment",
            "CustomerRef",
            "DocNumber",
            "Id",
            "PaymentType",
            "ProjectRef",
            "TxnDate",
        ),
        sortable=(
            "Balance",
            "CheckPayment",
            "CreditCardPayment",
            "DocNumber",
            "PaymentType",
            "TxnDate",
        ),
    ),
    "ReimburseCharge": EntitySpec(
        name="ReimburseCharge",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ}),
        required=(
            "Line",
            "Amount",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=("CurrencyRef",),
        filterable=(
            "CustomerRef",
            "HasBeenInvoiced",
            "Id",
        ),
        sortable=(),
    ),
    "SalesReceipt": EntitySpec(
        name="SalesReceipt",
        path="salesreceipt",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.PDF,
                Operation.QUERY,
                Operation.READ,
                Operation.SEND,
                Operation.UPDATE,
            }
        ),
        required=(
            "Line",
            "CustomerRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "ShipFromAddr",
            "CurrencyRef",
            "GlobalTaxCalculation",
            "ProjectRef",
            "BillEmail",
        ),
        filterable=(
            "Balance",
            "CustomerRef",
            "DocNumber",
            "Id",
            "ProjectRef",
            "TotalAmt",
            "TxnDate",
        ),
        sortable=(
            "Balance",
            "DocNumber",
            "TxnDate",
        ),
    ),
    "TaxAgency": EntitySpec(
        name="TaxAgency",
        path="taxagency",
        operations=frozenset({Operation.CREATE, Operation.QUERY, Operation.READ}),
        required=("DisplayName",),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=("Id",),
        sortable=("DisplayName",),
    ),
    "TaxClassification": EntitySpec(
        name="TaxClassification",
        path="taxclassification",
        operations=frozenset({Operation.READ}),
        required=("ParentRef",),
        required_for_update=(),
        conditionally_required=(),
        filterable=(),
        sortable=(),
    ),
    "TaxCode": EntitySpec(
        name="TaxCode",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ}),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "PurchaseTaxRateList",
            "SalesTaxRateList",
        ),
        filterable=(
            "Active",
            "Description",
            "Id",
            "Name",
        ),
        sortable=(
            "Description",
            "Name",
        ),
    ),
    "TaxPayment": EntitySpec(
        name="TaxPayment",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ}),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Id",
            "MetaData",
        ),
        sortable=("MetaData",),
    ),
    "TaxRate": EntitySpec(
        name="TaxRate",
        path="query",
        operations=frozenset({Operation.QUERY, Operation.READ}),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Active",
            "AgencyRef",
            "Description",
            "Id",
            "Name",
            "TaxReturnLineRef",
        ),
        sortable=(
            "Active",
            "AgencyRef",
            "Description",
            "Name",
            "TaxReturnLineRef",
        ),
    ),
    "TaxService": EntitySpec(
        name="TaxService",
        path="taxservice",
        operations=frozenset({Operation.CREATE}),
        required=(
            "TaxCode",
            "TaxRateDetails",
        ),
        required_for_update=(),
        conditionally_required=(),
        filterable=(),
        sortable=(),
    ),
    "Term": EntitySpec(
        name="Term",
        path="term",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("Name",),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Active",
            "Id",
            "Name",
        ),
        sortable=(
            "Active",
            "Name",
        ),
    ),
    "TimeActivity": EntitySpec(
        name="TimeActivity",
        path="timeactivity",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=("NameOf",),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "TxnDate",
            "BreakHours BreakMinutes",
            "EndTime",
            "Hours",
            "VendorRef",
            "ProjectRef",
            "HourlyRate",
            "CustomerRef",
            "EmployeeRef",
            "StartTime",
        ),
        filterable=(
            "BillableStatus",
            "Id",
            "ProjectRef",
            "TxnDate",
        ),
        sortable=("TxnDate",),
    ),
    "Transfer": EntitySpec(
        name="Transfer",
        path="transfer",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "ToAccountRef",
            "Amount",
            "FromAccountRef",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(),
        filterable=(
            "Id",
            "TxnDate",
        ),
        sortable=("TxnDate",),
    ),
    "Vendor": EntitySpec(
        name="Vendor",
        path="vendor",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "Title",
            "GivenName",
            "MiddleName",
            "Suffix",
            "FamilyName",
        ),
        filterable=(
            "Active",
            "Balance",
            "CompanyName",
            "DisplayName",
            "FamilyName",
            "GivenName",
            "Id",
            "MiddleName",
            "PrintOnCheckName",
            "Suffix",
        ),
        sortable=(
            "Active",
            "Balance",
            "CompanyName",
            "DisplayName",
            "FamilyName",
            "GivenName",
            "MiddleName",
            "PrintOnCheckName",
            "Suffix",
        ),
    ),
    "VendorCredit": EntitySpec(
        name="VendorCredit",
        path="vendorcredit",
        operations=frozenset(
            {
                Operation.CREATE,
                Operation.DELETE,
                Operation.QUERY,
                Operation.READ,
                Operation.UPDATE,
            }
        ),
        required=(
            "VendorRef",
            "Line",
        ),
        required_for_update=("SyncToken",),
        conditionally_required=(
            "GlobalTaxCalculation",
            "CurrencyRef",
        ),
        filterable=(
            "APAccountRef",
            "DocNumber",
            "Id",
            "TotalAmt",
            "TxnDate",
        ),
        sortable=(
            "APAccountRef",
            "Balance",
            "DocNumber",
            "TotalAmt",
            "TxnDate",
        ),
    ),
}

#: Every documented report, keyed by its documentation name.
REPORTS: Final[Mapping[str, ReportSpec]] = {
    "APAgingDetail": ReportSpec(
        name="APAgingDetail",
        route="AgedPayableDetail",
        variants=(),
    ),
    "APAgingSummary": ReportSpec(
        name="APAgingSummary",
        route="AgedPayables",
        variants=(),
    ),
    "ARAgingDetail": ReportSpec(
        name="ARAgingDetail",
        route="AgedReceivableDetail",
        variants=(),
    ),
    "ARAgingSummary": ReportSpec(
        name="ARAgingSummary",
        route="AgedReceivables",
        variants=(),
    ),
    "AccountListDetail": ReportSpec(
        name="AccountListDetail",
        route="AccountList",
        variants=(),
    ),
    "BalanceSheet": ReportSpec(
        name="BalanceSheet",
        route="BalanceSheet",
        variants=(),
    ),
    "CashFlow": ReportSpec(
        name="CashFlow",
        route="CashFlow",
        variants=(),
    ),
    "CustomerBalance": ReportSpec(
        name="CustomerBalance",
        route="CustomerBalance",
        variants=(),
    ),
    "CustomerBalanceDetail": ReportSpec(
        name="CustomerBalanceDetail",
        route="CustomerBalanceDetail",
        variants=(),
    ),
    "CustomerIncome": ReportSpec(
        name="CustomerIncome",
        route="CustomerIncome",
        variants=(),
    ),
    "GeneralLedger": ReportSpec(
        name="GeneralLedger",
        route="GeneralLedger",
        variants=(),
    ),
    "InventoryValuationDetail": ReportSpec(
        name="InventoryValuationDetail",
        route="InventoryValuationDetail",
        variants=(),
    ),
    "InventoryValuationSummary": ReportSpec(
        name="InventoryValuationSummary",
        route="InventoryValuationSummary",
        variants=(),
    ),
    "JournalReport": ReportSpec(
        name="JournalReport",
        route="JournalReport",
        variants=(),
    ),
    "ProfitAndLoss": ReportSpec(
        name="ProfitAndLoss",
        route="ProfitAndLoss",
        variants=(),
    ),
    "ProfitAndLossDetail": ReportSpec(
        name="ProfitAndLossDetail",
        route="ProfitAndLossDetail",
        variants=(),
    ),
    "SalesByClassSummary": ReportSpec(
        name="SalesByClassSummary",
        route="ClassSales",
        variants=(),
    ),
    "SalesByCustomer": ReportSpec(
        name="SalesByCustomer",
        route="CustomerSales",
        variants=(),
    ),
    "SalesByDepartment": ReportSpec(
        name="SalesByDepartment",
        route="DepartmentSales",
        variants=(),
    ),
    "SalesByProduct": ReportSpec(
        name="SalesByProduct",
        route="ItemSales",
        variants=(),
    ),
    "TaxSummary": ReportSpec(
        name="TaxSummary",
        route="TaxSummary",
        variants=(),
    ),
    "TransactionList": ReportSpec(
        name="TransactionList",
        route="TransactionList",
        variants=(),
    ),
    "TransactionListByCustomer": ReportSpec(
        name="TransactionListByCustomer",
        route="TransactionListByCustomer",
        variants=(),
    ),
    "TransactionListByVendor": ReportSpec(
        name="TransactionListByVendor",
        route="TransactionListByVendor",
        variants=(),
    ),
    "TransactionListWithSplits": ReportSpec(
        name="TransactionListWithSplits",
        route="TransactionListWithSplits",
        variants=(),
    ),
    "TrialBalance": ReportSpec(
        name="TrialBalance",
        route="TrialBalance",
        variants=("TrialBalanceFR",),
    ),
    "VendorBalance": ReportSpec(
        name="VendorBalance",
        route="VendorBalance",
        variants=(),
    ),
    "VendorBalanceDetail": ReportSpec(
        name="VendorBalanceDetail",
        route="VendorBalanceDetail",
        variants=(),
    ),
    "VendorExpenses": ReportSpec(
        name="VendorExpenses",
        route="VendorExpenses",
        variants=(),
    ),
}

#: Reverse lookup: every callable route -> the documentation name.
REPORT_ROUTES: Final[Mapping[str, str]] = {
    "AgedPayableDetail": "APAgingDetail",
    "AgedPayables": "APAgingSummary",
    "AgedReceivableDetail": "ARAgingDetail",
    "AgedReceivables": "ARAgingSummary",
    "AccountList": "AccountListDetail",
    "BalanceSheet": "BalanceSheet",
    "CashFlow": "CashFlow",
    "CustomerBalance": "CustomerBalance",
    "CustomerBalanceDetail": "CustomerBalanceDetail",
    "CustomerIncome": "CustomerIncome",
    "GeneralLedger": "GeneralLedger",
    "InventoryValuationDetail": "InventoryValuationDetail",
    "InventoryValuationSummary": "InventoryValuationSummary",
    "JournalReport": "JournalReport",
    "ProfitAndLoss": "ProfitAndLoss",
    "ProfitAndLossDetail": "ProfitAndLossDetail",
    "ClassSales": "SalesByClassSummary",
    "CustomerSales": "SalesByCustomer",
    "DepartmentSales": "SalesByDepartment",
    "ItemSales": "SalesByProduct",
    "TaxSummary": "TaxSummary",
    "TransactionList": "TransactionList",
    "TransactionListByCustomer": "TransactionListByCustomer",
    "TransactionListByVendor": "TransactionListByVendor",
    "TransactionListWithSplits": "TransactionListWithSplits",
    "TrialBalanceFR": "TrialBalance",
    "TrialBalance": "TrialBalance",
    "VendorBalance": "VendorBalance",
    "VendorBalanceDetail": "VendorBalanceDetail",
    "VendorExpenses": "VendorExpenses",
}


def entity_names() -> frozenset[str]:
    """Every documented entity name."""
    return frozenset(ENTITIES)


def report_names() -> frozenset[str]:
    """Every documented report name."""
    return frozenset(REPORTS)


def report_route(name: str) -> str:
    """Resolve a report name to the route the API actually takes.

    Accepts either the documentation name or the route itself, because
    callers reasonably use whichever they read first.
    """
    spec = REPORTS.get(name)
    if spec is not None:
        return spec.route
    documented = REPORT_ROUTES.get(name)
    if documented is not None:
        return REPORTS[documented].route
    raise KeyError(
        f"Unknown report {name!r}. Known reports: " + ", ".join(sorted(REPORTS))
    )


def supports(entity: str, operation: Operation) -> bool:
    """Whether ``entity`` documents ``operation``."""
    spec = ENTITIES.get(entity)
    return spec is not None and operation in spec.operations
