"""Pydantic models for the QuickBooks Online Accounting API.

GENERATED by ``tools/generate_models.py``. Do not edit by hand.

Structure and field requirements come from the documentation JSON;
enum members come from the XSD, which is the only source that lists
them. See ``API_COVERAGE.md``.

Every field is optional. A response model that refuses to parse a
response the API legitimately returned is worse than one that admits
a field was absent -- partial reads, sparse updates and locale
differences all produce valid responses missing documented fields.
Request-side requirements are declared on ``EntitySpec`` in
``qbo.entities`` and enforced there instead.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict


class QboModel(BaseModel):
    """Base for every generated model.

    ``extra="allow"`` is deliberate: QuickBooks adds fields in new
    minorversions, and dropping them silently is how a field that
    exists on the wire becomes invisible to callers. Unknown fields
    are kept and reachable through ``model_extra``.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
        str_strip_whitespace=True,
    )


class AccountTypeEnum(StrEnum):
    """AccountTypeEnum, values from the XSD."""

    BANK = "Bank"
    ACCOUNTS_RECEIVABLE = "Accounts Receivable"
    OTHER_CURRENT_ASSET = "Other Current Asset"
    FIXED_ASSET = "Fixed Asset"
    OTHER_ASSET = "Other Asset"
    ACCOUNTS_PAYABLE = "Accounts Payable"
    CREDIT_CARD = "Credit Card"
    OTHER_CURRENT_LIABILITY = "Other Current Liability"
    LONG_TERM_LIABILITY = "Long Term Liability"
    EQUITY = "Equity"
    INCOME = "Income"
    COST_OF_GOODS_SOLD = "Cost of Goods Sold"
    EXPENSE = "Expense"
    OTHER_INCOME = "Other Income"
    OTHER_EXPENSE = "Other Expense"
    NON_POSTING = "Non-Posting"


class BillPaymentTypeEnum(StrEnum):
    """BillPaymentTypeEnum, values from the XSD."""

    CHECK = "Check"
    CREDITCARD = "CreditCard"


class BillableStatusEnum(StrEnum):
    """BillableStatusEnum, values from the XSD."""

    BILLABLE = "Billable"
    NOTBILLABLE = "NotBillable"
    HASBEENBILLED = "HasBeenBilled"


class BudgetEntryTypeEnum(StrEnum):
    """BudgetEntryTypeEnum, values from the XSD."""

    YEARLY = "Yearly"
    QUARTERLY = "Quarterly"
    MONTHLY = "Monthly"


class BudgetTypeEnum(StrEnum):
    """BudgetTypeEnum, values from the XSD."""

    PROFITANDLOSS = "ProfitAndLoss"
    BALANCESHEET = "BalanceSheet"


class CCPaymentStatusEnum(StrEnum):
    """CCPaymentStatusEnum, values from the XSD."""

    COMPLETED = "Completed"
    VOIDED = "Voided"
    UNKNOWN = "Unknown"


class CustomFieldTypeEnum(StrEnum):
    """CustomFieldTypeEnum, values from the XSD."""

    STRINGTYPE = "StringType"
    BOOLEANTYPE = "BooleanType"
    NUMBERTYPE = "NumberType"
    DATETYPE = "DateType"


class DeliveryTypeEnum(StrEnum):
    """DeliveryTypeEnum, values from the XSD."""

    EMAIL = "Email"
    TRADESHIFT = "Tradeshift"


class EntityTypeEnum(StrEnum):
    """EntityTypeEnum, values from the XSD."""

    CUSTOMER = "Customer"
    EMPLOYEE = "Employee"
    JOB = "Job"
    OTHER = "Other"
    VENDOR = "Vendor"


class GlobalTaxCalculationEnum(StrEnum):
    """GlobalTaxCalculationEnum, values from the XSD."""

    TAXINCLUSIVE = "TaxInclusive"
    TAXEXCLUDED = "TaxExcluded"
    NOTAPPLICABLE = "NotApplicable"


class ItemTypeEnum(StrEnum):
    """ItemTypeEnum, values from the XSD."""

    ASSEMBLY = "Assembly"
    CATEGORY = "Category"
    FIXED_ASSET = "Fixed Asset"
    GROUP = "Group"
    INVENTORY = "Inventory"
    NONINVENTORY = "NonInventory"
    OTHER_CHARGE = "Other Charge"
    PAYMENT = "Payment"
    SERVICE = "Service"
    SUBTOTAL = "Subtotal"
    DISCOUNT = "Discount"
    TAX = "Tax"
    TAX_GROUP = "Tax Group"
    BUNDLE = "Bundle"


class LineDetailTypeEnum(StrEnum):
    """LineDetailTypeEnum, values from the XSD."""

    PAYMENTLINEDETAIL = "PaymentLineDetail"
    DISCOUNTLINEDETAIL = "DiscountLineDetail"
    TAXLINEDETAIL = "TaxLineDetail"
    SALESITEMLINEDETAIL = "SalesItemLineDetail"
    ITEMBASEDEXPENSELINEDETAIL = "ItemBasedExpenseLineDetail"
    ACCOUNTBASEDEXPENSELINEDETAIL = "AccountBasedExpenseLineDetail"
    DEPOSITLINEDETAIL = "DepositLineDetail"
    PURCHASEORDERITEMLINEDETAIL = "PurchaseOrderItemLineDetail"
    ITEMRECEIPTLINEDETAIL = "ItemReceiptLineDetail"
    JOURNALENTRYLINEDETAIL = "JournalEntryLineDetail"
    GROUPLINEDETAIL = "GroupLineDetail"
    DESCRIPTIONONLY = "DescriptionOnly"
    SUBTOTALLINEDETAIL = "SubTotalLineDetail"
    SALESORDERITEMLINEDETAIL = "SalesOrderItemLineDetail"
    TDSLINEDETAIL = "TDSLineDetail"
    REIMBURSELINEDETAIL = "ReimburseLineDetail"
    ITEMADJUSTMENTLINEDETAIL = "ItemAdjustmentLineDetail"


class MonthEnum(StrEnum):
    """MonthEnum, values from the XSD."""

    JANUARY = "January"
    FEBRUARY = "February"
    MARCH = "March"
    APRIL = "April"
    MAY = "May"
    JUNE = "June"
    JULY = "July"
    AUGUST = "August"
    SEPTEMBER = "September"
    OCTOBER = "October"
    NOVEMBER = "November"
    DECEMBER = "December"


class PaymentTypeEnum(StrEnum):
    """PaymentTypeEnum, values from the XSD."""

    CASH = "Cash"
    CHECK = "Check"
    CREDITCARD = "CreditCard"
    EXPENSE = "Expense"
    OTHER = "Other"


class PostingTypeEnum(StrEnum):
    """PostingTypeEnum, values from the XSD."""

    CREDIT = "Credit"
    DEBIT = "Debit"


class PrintStatusEnum(StrEnum):
    """PrintStatusEnum, values from the XSD."""

    NOTSET = "NotSet"
    NEEDTOPRINT = "NeedToPrint"
    PRINTCOMPLETE = "PrintComplete"


class ReportBasisEnum(StrEnum):
    """ReportBasisEnum, values from the XSD."""

    ACCRUAL = "Accrual"
    CASH = "Cash"


class TaxApplicableOnEnum(StrEnum):
    """TaxApplicableOnEnum, values from the XSD."""

    PURCHASE = "Purchase"
    SALES = "Sales"


class TxnTypeEnum(StrEnum):
    """TxnTypeEnum, values from the XSD."""

    APCREDITCARD = "APCreditCard"
    ARREFUNDCREDITCARD = "ARRefundCreditCard"
    BILL = "Bill"
    BILLPAYMENTCHECK = "BillPaymentCheck"
    BUILDASSEMBLY = "BuildAssembly"
    CARRYOVER = "CarryOver"
    CASHPURCHASE = "CashPurchase"
    CHARGE = "Charge"
    CHECK = "Check"
    CREDITCARDPAYMENT = "CreditCardPayment"
    CREDITMEMO = "CreditMemo"
    DEPOSIT = "Deposit"
    EFPLIABILITYCHECK = "EFPLiabilityCheck"
    EFTBILLPAYMENT = "EFTBillPayment"
    EFTREFUND = "EFTRefund"
    ESTIMATE = "Estimate"
    INVENTORYADJUSTMENT = "InventoryAdjustment"
    INVENTORYTRANSFER = "InventoryTransfer"
    INVOICE = "Invoice"
    ITEMRECEIPT = "ItemReceipt"
    JOURNALENTRY = "JournalEntry"
    LIABILITYADJUSTMENT = "LiabilityAdjustment"
    PAYCHECK = "Paycheck"
    PAYROLLLIABILITYCHECK = "PayrollLiabilityCheck"
    PURCHASEORDER = "PurchaseOrder"
    PRIORPAYMENT = "PriorPayment"
    RECEIVEPAYMENT = "ReceivePayment"
    REFUNDCHECK = "RefundCheck"
    REIMBURSECHARGE = "ReimburseCharge"
    SALESORDER = "SalesOrder"
    SALESRECEIPT = "SalesReceipt"
    SALESTAXPAYMENTCHECK = "SalesTaxPaymentCheck"
    TRANSFER = "Transfer"
    TIMEACTIVITY = "TimeActivity"
    VENDORCREDIT = "VendorCredit"
    VENDORPREPAYMENT = "VendorPrepayment"
    YTDADJUSTMENT = "YTDAdjustment"


class WeekEnum(StrEnum):
    """WeekEnum, values from the XSD."""

    SUNDAY = "Sunday"
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"


class Account_(QboModel):
    """Account."""

    SyncToken: str | None = None
    SubAccount: bool | None = None
    Classification: str | None = None
    FullyQualifiedName: str | None = None
    AccountType: AccountTypeEnum | None = None
    CurrencyRef: CurrencyRef_ | None = None
    CurrentBalanceWithSubAccounts: Decimal | None = None
    AcctNum: str | None = None
    TaxCodeRef: ReferenceType_ | None = None
    ParentRef: ReferenceType_ | None = None
    AccountSubType: str | None = None
    CurrentBalance: Decimal | None = None
    Description: str | None = None
    Active: bool | None = None
    MetaData: ModificationMetadata_ | None = None
    Id: str | None = None
    Name: str | None = None


class AccountBasedExpenseLine_(QboModel):
    """AccountBasedExpenseLine."""

    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    Id: str | None = None
    AccountBasedExpenseLineDetail: AccountBasedExpenseLineDetail_ | None = None


class AccountBasedExpenseLineBill_(QboModel):
    """AccountBasedExpenseLineBill."""

    LinkedTxn: list[dict[str, Any]] | None = None
    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    Id: str | None = None
    AccountBasedExpenseLineDetail: AccountBasedExpenseLineDetail_ | None = None


class AccountBasedExpenseLineDetail_(QboModel):
    """AccountBasedExpenseLineDetail."""

    TaxAmount: Decimal | None = None
    TaxInclusiveAmt: Decimal | None = None
    ClassRef: ReferenceType_ | None = None
    TaxCodeRef: ReferenceType_ | None = None
    MarkupInfo: MarkupInfo_ | None = None
    BillableStatus: BillableStatusEnum | None = None
    AccountRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None


class AccountingInfoPrefs_(QboModel):
    """AccountingInfoPrefs."""

    FirstMonthOfFiscalYear: MonthEnum | None = None
    UseAccountNumbers: bool | None = None
    TaxYearMonth: str | None = None
    ClassTrackingPerTxn: bool | None = None
    TrackDepartments: bool | None = None
    TaxForm: str | None = None
    CustomerTerminology: str | None = None
    BookCloseDate: date | None = None
    DepartmentTerminology: str | None = None
    ClassTrackingPerTxnLine: bool | None = None


class AssociatedValues_(QboModel):
    """AssociatedValues."""

    Value: str | None = None
    Key: str | None = None


class Attachable_(QboModel):
    """Attachable."""

    Category: str | None = None
    SyncToken: str | None = None
    FileAccessUri: str | None = None
    ContentType: str | None = None
    PlaceName: str | None = None
    Size: Decimal | None = None
    AttachableRef: AttachableRef_ | None = None
    Long: str | None = None
    FileName: str | None = None
    Note: str | None = None
    Tag: str | None = None
    Lat: str | None = None
    ThumbnailFileAccessUri: str | None = None
    TempDownloadUri: str | None = None
    ThumbnailTempDownloadUri: str | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class AttachableRef_(QboModel):
    """AttachableRef."""

    IncludeOnSend: bool | None = None
    LineInfo: str | None = None
    NoRefOnly: bool | None = None
    CustomField: list[CustomField_] | None = None
    Inactive: bool | None = None
    EntityRef: ReferenceType_ | None = None


class Bill_(QboModel):
    """Bill."""

    TxnDate: date | None = None
    CurrencyRef: CurrencyRef_ | None = None
    APAccountRef: ReferenceType_ | None = None
    HomeBalance: Decimal | None = None
    SalesTermRef: ReferenceType_ | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    DueDate: date | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    VendorRef: ReferenceType_ | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: list[AccountBasedExpenseLineBill_ | ItemBasedExpenseLineBill_] | None = None
    Balance: Decimal | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    ExchangeRate: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    IncludeInAnnualTPAR: bool | None = None
    Id: str | None = None


class BillPayment_(QboModel):
    """BillPayment."""

    DocNumber: str | None = None
    SyncToken: str | None = None
    PrivateNote: str | None = None
    VendorRef: ReferenceType_ | None = None
    Line: list[LineLinkedTxn_] | None = None
    TxnDate: date | None = None
    TotalAmt: Decimal | None = None
    ExchangeRate: Decimal | None = None
    APAccountRef: ReferenceType_ | None = None
    PayType: BillPaymentTypeEnum | None = None
    DepartmentRef: ReferenceType_ | None = None
    CheckPayment: BillPaymentCheck_ | None = None
    CreditCardPayment: BillPaymentCreditCard_ | None = None
    ProcessBillPayment: bool | None = None
    Id: str | None = None
    CurrencyRef: CurrencyRef_ | None = None
    MetaData: ModificationMetadata_ | None = None


class BillPaymentCheck_(QboModel):
    """BillPaymentCheck."""

    PrintStatus: PrintStatusEnum | None = None
    BankAccountRef: ReferenceType_ | None = None


class BillPaymentCreditCard_(QboModel):
    """BillPaymentCreditCard."""

    CCAccountRef: ReferenceType_ | None = None


class Budget_(QboModel):
    """Budget."""

    SyncToken: str | None = None
    BudgetEntryType: BudgetEntryTypeEnum | None = None
    EndDate: datetime | None = None
    Name: str | None = None
    BudgetDetail: list[BudgetDetail_] | None = None
    StartDate: datetime | None = None
    BudgetType: BudgetTypeEnum | None = None
    CustomExtensions: CustomExtensions_ | None = None
    Active: bool | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class BudgetDetail_(QboModel):
    """BudgetDetail."""

    ClassRef: ReferenceType_ | None = None
    DepartmentRef: ReferenceType_ | None = None
    Amount: Decimal | None = None
    BudgetDate: datetime | None = None
    AccountRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None


class CashbackInfo_(QboModel):
    """CashbackInfo."""

    AccountRef: ReferenceType_ | None = None
    Amount: str | None = None
    Memo: str | None = None


class ChangeOrder_(QboModel):
    """ChangeOrder."""

    TxnDate: date | None = None
    PrintStatus: str | None = None
    TxnStatus: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    TotalAmt: Decimal | None = None
    AcceptedDate: date | None = None
    ExpirationDate: date | None = None
    ApplyTaxAfterDiscount: bool | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    Line: list[SalesItemLine_ | SubTotalLine_] | None = None
    CustomerMemo: MemoRef_ | None = None
    ProjectRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    AcceptedBy: str | None = None
    TotalCostAmount: Decimal | None = None
    EmailStatus: str | None = None
    MetaData: ModificationMetadata_ | None = None
    BillEmail: EmailAddress_ | None = None
    Id: str | None = None


class CheckPayment_(QboModel):
    """CheckPayment."""

    CheckNum: str | None = None
    Status: str | None = None
    NameOnAcct: str | None = None
    AcctNum: str | None = None
    BankName: str | None = None


class Class_(QboModel):
    """Class."""

    SyncToken: str | None = None
    Name: str | None = None
    FullyQualifiedName: str | None = None
    SubClass: bool | None = None
    ParentRef: ReferenceType_ | None = None
    Active: bool | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class CompanyCurrency_(QboModel):
    """CompanyCurrency."""

    SyncToken: str | None = None
    Code: str | None = None
    Name: str | None = None
    CustomField: CustomField_ | None = None
    Active: bool | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class CompanyInfo_(QboModel):
    """CompanyInfo."""

    SyncToken: str | None = None
    LegalAddr: PhysicalAddress_ | None = None
    SupportedLanguages: str | None = None
    CompanyName: str | None = None
    Country: str | None = None
    CompanyAddr: PhysicalAddress_ | None = None
    Email: EmailAddress_ | None = None
    WebAddr: WebsiteAddress_ | None = None
    NameValue: list[dict[str, Any]] | None = None
    FiscalYearStartMonth: MonthEnum | None = None
    CustomerCommunicationAddr: PhysicalAddress_ | None = None
    PrimaryPhone: TelephoneNumber_ | None = None
    LegalName: str | None = None
    CompanyStartDate: datetime | None = None
    EmployerId: str | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class ContactInfo_(QboModel):
    """ContactInfo."""

    Type: str | None = None
    Telephone: dict[str, Any] | None = None


class CreditCardPayment_(QboModel):
    """CreditCardPayment."""

    SyncToken: str | None = None
    PrivateNote: str | None = None
    VendorRef: ReferenceType_ | None = None
    CreditCardAccountRef: ReferenceType_ | None = None
    TxnDate: date | None = None
    Memo: str | None = None
    PrintStatus: str | None = None
    CheckNum: str | None = None
    Amount: Decimal | None = None
    BankAccountRef: ReferenceType_ | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class CreditCardPaymentDetail_(QboModel):
    """CreditCardPaymentDetail."""

    CreditChargeResponse: CreditChargeResponse_ | None = None
    CreditChargeInfo: CreditChargeInfo_ | None = None


class CreditChargeInfo_(QboModel):
    """CreditChargeInfo."""

    CcExpiryMonth: int | None = None
    ProcessPayment: bool | None = None
    PostalCode: str | None = None
    Amount: Decimal | None = None
    NameOnAcct: str | None = None
    CcExpiryYear: int | None = None
    Type: str | None = None
    BillAddrStreet: str | None = None


class CreditChargeResponse_(QboModel):
    """CreditChargeResponse."""

    Status: CCPaymentStatusEnum | None = None
    AuthCode: str | None = None
    TxnAuthorizationTime: datetime | None = None
    CCTransId: str | None = None


class CreditMemo_(QboModel):
    """CreditMemo."""

    TxnDate: date | None = None
    CurrencyRef: CurrencyRef_ | None = None
    CustomField: CustomField_ | None = None
    HomeBalance: Decimal | None = None
    ClassRef: ReferenceType_ | None = None
    PrintStatus: str | None = None
    SalesTermRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    RemainingCredit: Decimal | None = None
    ApplyTaxAfterDiscount: bool | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: (
        list[
            DescriptionOnlyLine_
            | DiscountLine_
            | GroupLine_
            | SalesItemLine_
            | SubTotalLine_
        ]
        | None
    ) = None
    CustomerMemo: MemoRef_ | None = None
    ProjectRef: ReferenceType_ | None = None
    TaxExemptionRef: ReferenceType_ | None = None
    Balance: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    ExchangeRate: Decimal | None = None
    ShipAddr: PhysicalAddress_ | None = None
    HomeTotalAmt: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    EmailStatus: str | None = None
    BillAddr: PhysicalAddress_ | None = None
    MetaData: ModificationMetadata_ | None = None
    BillEmail: EmailAddress_ | None = None
    Id: str | None = None


class CurrencyPrefs_(QboModel):
    """CurrencyPrefs."""

    HomeCurrency: dict[str, Any] | None = None
    MultiCurrencyEnabled: bool | None = None


class CurrencyRef_(QboModel):
    """CurrencyRef."""

    name: str | None = None
    value: str | None = None


class CustomExtensions_(QboModel):
    """CustomExtensions."""

    AssociatedValues: AssociatedValues_ | None = None
    ExtensionType: str | None = None


class CustomField_(QboModel):
    """CustomField."""

    DefinitionId: str | None = None
    StringValue: str | None = None
    Type: CustomFieldTypeEnum | None = None
    Name: str | None = None


class CustomFieldBoolpo_(QboModel):
    """CustomFieldBoolpo."""

    BooleanValue: bool | None = None
    Type: CustomFieldTypeEnum | None = None
    Name: str | None = None


class CustomFieldBoolsales_(QboModel):
    """CustomFieldBoolsales."""

    BooleanValue: bool | None = None
    Type: CustomFieldTypeEnum | None = None
    Name: str | None = None


class CustomFieldStringpo_(QboModel):
    """CustomFieldStringpo."""

    StringValue: str | None = None
    Type: CustomFieldTypeEnum | None = None
    Name: str | None = None


class CustomFieldStringsales_(QboModel):
    """CustomFieldStringsales."""

    StringValue: str | None = None
    Type: CustomFieldTypeEnum | None = None
    Name: str | None = None


class Customer_(QboModel):
    """Customer."""

    PrimaryEmailAddr: EmailAddress_ | None = None
    DisplayName: str | None = None
    Title: str | None = None
    ResaleNum: str | None = None
    SecondaryTaxIdentifier: str | None = None
    DefaultTaxCodeRef: ReferenceType_ | None = None
    PreferredDeliveryMethod: str | None = None
    GivenName: str | None = None
    SalesTermRef: ReferenceType_ | None = None
    CustomerTypeRef: CustomerTypeRef_ | None = None
    FullyQualifiedName: str | None = None
    Fax: TelephoneNumber30_ | None = None
    BillWithParent: bool | None = None
    CurrencyRef: ReferenceType_ | None = None
    Mobile: TelephoneNumber30_ | None = None
    Job: bool | None = None
    BalanceWithJobs: Decimal | None = None
    PrimaryPhone: TelephoneNumber30_ | None = None
    OpenBalanceDate: date | None = None
    Taxable: bool | None = None
    AlternatePhone: TelephoneNumber30_ | None = None
    MetaData: ModificationMetadata_ | None = None
    ParentRef: ReferenceType_ | None = None
    Level: int | None = None
    MiddleName: str | None = None
    Notes: str | None = None
    TaxExemptionReasonId: dict[str, Any] | None = None
    WebAddr: WebsiteAddress_ | None = None
    Active: bool | None = None
    CompanyName: str | None = None
    Balance: Decimal | None = None
    SyncToken: str | None = None
    ShipAddr: PhysicalAddress_ | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    Suffix: str | None = None
    IsProject: bool | None = None
    Source: str | None = None
    FamilyName: str | None = None
    PrimaryTaxIdentifier: str | None = None
    PrintOnCheckName: str | None = None
    BillAddr: PhysicalAddress_ | None = None
    Id: str | None = None


class CustomerType_(QboModel):
    """CustomerType."""

    Active: bool | None = None
    SyncToken: str | None = None
    MetaData: ModificationMetadata_ | None = None
    Name: str | None = None
    Id: str | None = None


class CustomerTypeRef_(QboModel):
    """CustomerTypeRef."""

    value: str | None = None


class DeliveryInfo_(QboModel):
    """DeliveryInfo."""

    DeliveryType: DeliveryTypeEnum | None = None
    DeliveryTime: datetime | None = None


class Department_(QboModel):
    """Department."""

    SyncToken: str | None = None
    Name: str | None = None
    FullyQualifiedName: str | None = None
    SubDepartment: bool | None = None
    ParentRef: ReferenceType_ | None = None
    Active: bool | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class Deposit_(QboModel):
    """Deposit."""

    SyncToken: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    DepositToAccountRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    ExchangeRate: Decimal | None = None
    CurrencyRef: CurrencyRef_ | None = None
    HomeTotalAmt: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    TxnSource: str | None = None
    TxnDate: date | None = None
    Line: list[DepositLine_ | LineLinkedTxn_] | None = None
    CashBack: CashbackInfo_ | None = None
    Id: str | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    MetaData: ModificationMetadata_ | None = None


class DepositLine_(QboModel):
    """DepositLine."""

    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    ProjectRef: ReferenceType_ | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    CustomField: CustomField_ | None = None
    Id: str | None = None
    DepositLineDetail: DepositLineDetail_ | None = None


class DepositLineDetail_(QboModel):
    """DepositLineDetail."""

    PaymentMethodRef: ReferenceType_ | None = None
    ClassRef: ReferenceType_ | None = None
    CheckNum: str | None = None
    TaxCodeRef: ReferenceType_ | None = None
    TaxApplicableOn: TaxApplicableOnEnum | None = None
    TxnType: TxnTypeEnum | None = None
    AccountRef: ReferenceType_ | None = None
    Entity: ReferenceType_ | None = None


class DescriptionOnly_(QboModel):
    """DescriptionOnly."""

    TaxCodeRef: ReferenceType_ | None = None
    ServiceDate: date | None = None


class DescriptionOnlyLine_(QboModel):
    """DescriptionOnlyLine."""

    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    DescriptionLineDetail: DescriptionOnly_ | None = None
    Id: str | None = None


class DiscountLine_(QboModel):
    """DiscountLine."""

    DiscountLineDetail: DiscountLineDetail_ | None = None
    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    Id: str | None = None


class DiscountLineDetail_(QboModel):
    """DiscountLineDetail."""

    ClassRef: ReferenceType_ | None = None
    TaxCodeRef: ReferenceType_ | None = None
    DiscountAccountRef: ReferenceType_ | None = None
    PercentBased: bool | None = None
    DiscountPercent: Decimal | None = None


class EffectiveTaxRatedata_(QboModel):
    """EffectiveTaxRatedata."""

    RateValue: Decimal | None = None
    EndDate: str | None = None
    EffectiveDate: str | None = None


class EmailAddress_(QboModel):
    """EmailAddress."""

    Address: str | None = None


class EmailMessageType_(QboModel):
    """EmailMessageType."""

    Message: str | None = None
    Subject: str | None = None


class EmailMessagesPrefs_(QboModel):
    """EmailMessagesPrefs."""

    InvoiceMessage: EmailMessageType_ | None = None
    EstimateMessage: EmailMessageType_ | None = None
    SalesReceiptMessage: EmailMessageType_ | None = None
    StatementMessage: EmailMessageType_ | None = None


class Employee_(QboModel):
    """Employee."""

    PrimaryEmailAddr: EmailAddress_ | None = None
    DisplayName: str | None = None
    Title: str | None = None
    BillableTime: bool | None = None
    GivenName: str | None = None
    V4IDPseudonym: str | None = None
    BirthDate: date | None = None
    MiddleName: str | None = None
    SSN: str | None = None
    PrimaryAddr: PhysicalAddress_ | None = None
    PrimaryPhone: TelephoneNumber_ | None = None
    Active: bool | None = None
    ReleasedDate: date | None = None
    MetaData: dict[str, Any] | None = None
    CostRate: Decimal | None = None
    Mobile: TelephoneNumber_ | None = None
    Gender: str | None = None
    HiredDate: date | None = None
    BillRate: Decimal | None = None
    Organization: bool | None = None
    SyncToken: str | None = None
    Suffix: str | None = None
    FamilyName: str | None = None
    PrintOnCheckName: str | None = None
    EmployeeNumber: str | None = None
    Id: str | None = None


class Entitlements_(QboModel):
    """Entitlements."""

    PlanName: str | None = None
    Entitlement: list[dict[str, Any]] | None = None
    SupportedLanguages: str | None = None
    CompanyStartDate: datetime | None = None
    EmployerId: str | None = None
    QboCompany: bool | None = None
    Email: EmailAddress_ | None = None
    WebAddr: WebsiteAddress_ | None = None
    FiscalYearStartMonth: MonthEnum | None = None
    Thresholds: list[Threshold_] | None = None
    DaysRemainingTrial: int | None = None
    MaxUsers: int | None = None
    CurrentUsers: int | None = None


class Entity_(QboModel):
    """Entity."""

    Type: EntityTypeEnum | None = None
    EntityRef: ReferenceType_ | None = None


class Estimate_(QboModel):
    """Estimate."""

    TxnDate: date | None = None
    ShipFromAddr: PhysicalAddress_ | None = None
    CurrencyRef: CurrencyRef_ | None = None
    ShipDate: date | None = None
    ClassRef: ReferenceType_ | None = None
    PrintStatus: str | None = None
    CustomField: CustomField_ | None = None
    SalesTermRef: ReferenceType_ | None = None
    TxnStatus: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    AcceptedDate: date | None = None
    ExpirationDate: date | None = None
    DueDate: date | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: (
        list[
            DescriptionOnlyLine_
            | DiscountLine_
            | GroupLine_
            | SalesItemLine_
            | SubTotalLine_
        ]
        | None
    ) = None
    CustomerMemo: MemoRef_ | None = None
    EmailStatus: str | None = None
    ProjectRef: ReferenceType_ | None = None
    TaxExemptionRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    AcceptedBy: str | None = None
    ExchangeRate: Decimal | None = None
    ShipAddr: PhysicalAddress_ | None = None
    HomeTotalAmt: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    ShipMethodRef: ReferenceType_ | None = None
    BillAddr: PhysicalAddress_ | None = None
    FreeFormAddress: bool | None = None
    ApplyTaxAfterDiscount: bool | None = None
    BillEmail: EmailAddress_ | None = None
    Id: str | None = None


class Exchangerate_(QboModel):
    """Exchangerate."""

    SyncToken: str | None = None
    AsOfDate: date | None = None
    CustomField: CustomField_ | None = None
    SourceCurrencyCode: str | None = None
    Rate: Decimal | None = None
    TargetCurrencyCode: str | None = None
    MetaData: ModificationMetadata_ | None = None


class GroupLine_(QboModel):
    """GroupLine."""

    Description: str | None = None
    GroupLineDetail: GroupLineDetail_ | None = None
    DetailType: LineDetailTypeEnum | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Id: str | None = None


class GroupLineDetail_(QboModel):
    """GroupLineDetail."""

    Quantity: Decimal | None = None
    Line: list[SalesItemLine_] | None = None
    GroupItemRef: ReferenceType_ | None = None


class InventoryAdjustment_(QboModel):
    """InventoryAdjustment."""

    DocNumber: str | None = None
    TxnDate: datetime | None = None
    PrivateNote: str | None = None
    SyncToken: str | None = None
    Line: list[ItemAdjustmentLine_] | None = None
    AdjustAccountRef: ReferenceType_ | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class Invoice_(QboModel):
    """Invoice."""

    TxnDate: date | None = None
    ShipFromAddr: PhysicalAddress_ | None = None
    CurrencyRef: CurrencyRef_ | None = None
    HomeBalance: Decimal | None = None
    ShipDate: date | None = None
    TrackingNum: str | None = None
    ClassRef: ReferenceType_ | None = None
    PrintStatus: str | None = None
    EmailStatus: str | None = None
    SalesTermRef: ReferenceType_ | None = None
    DeliveryInfo: DeliveryInfo_ | None = None
    TxnSource: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    DepositToAccountRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    AllowOnlineAffirmPayment: bool | None = None
    InvoiceLink: str | None = None
    AllowOnlineACHPayment: bool | None = None
    TransactionLocationType: str | None = None
    DueDate: date | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: (
        list[
            DescriptionOnlyLine_
            | DiscountLine_
            | GroupLine_
            | SalesItemLine_
            | SubTotalLine_
        ]
        | None
    ) = None
    BillEmailCc: EmailAddress_ | None = None
    CustomerMemo: MemoRef_ | None = None
    AllowOnlinePayPalPayment: bool | None = None
    ProjectRef: ReferenceType_ | None = None
    ExchangeRate: Decimal | None = None
    TaxExemptionRef: ReferenceType_ | None = None
    Deposit: Decimal | None = None
    Balance: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    AllowOnlineCreditCardPayment: bool | None = None
    SyncToken: str | None = None
    CustomField: CustomField_ | None = None
    ShipAddr: PhysicalAddress_ | None = None
    HomeTotalAmt: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    BillEmailBcc: EmailAddress_ | None = None
    ShipMethodRef: ReferenceType_ | None = None
    BillAddr: PhysicalAddress_ | None = None
    FreeFormAddress: bool | None = None
    ApplyTaxAfterDiscount: bool | None = None
    BillEmail: EmailAddress_ | None = None
    Id: str | None = None
    AllowOnlinePayment: bool | None = None
    AllowIPNPayment: bool | None = None


class Item_(QboModel):
    """Item."""

    Sku: str | None = None
    SalesTaxIncluded: bool | None = None
    TrackQtyOnHand: bool | None = None
    SalesTaxCodeRef: ReferenceType_ | None = None
    CustomExtensions: CustomExtensions_ | None = None
    Source: str | None = None
    InvStartDate: date | None = None
    Type: str | None = None
    PurchaseTaxIncluded: bool | None = None
    FullyQualifiedName: str | None = None
    Description: str | None = None
    SubItem: bool | None = None
    Taxable: bool | None = None
    ReorderPoint: Decimal | None = None
    PurchaseDesc: str | None = None
    MetaData: ModificationMetadata_ | None = None
    PrefVendorRef: ReferenceType_ | None = None
    Name: str | None = None
    Level: int | None = None
    IncomeAccountRef: ReferenceType_ | None = None
    Active: bool | None = None
    ClassRef: ReferenceType_ | None = None
    ExpenseAccountRef: ReferenceType_ | None = None
    TaxClassificationRef: ReferenceType_ | None = None
    PurchaseTaxCodeRef: ReferenceType_ | None = None
    SyncToken: str | None = None
    PurchaseCost: Decimal | None = None
    QtyOnHand: Decimal | None = None
    AssetAccountRef: ReferenceType_ | None = None
    ParentRef: ReferenceType_ | None = None
    UnitPrice: Decimal | None = None
    Id: str | None = None


class ItemAdjustmentLine_(QboModel):
    """ItemAdjustmentLine."""

    DetailType: LineDetailTypeEnum | None = None
    CustomExtensions: CustomExtensions_ | None = None
    ItemAdjustmentLineDetail: ItemAdjustmentLineDetail_ | None = None
    Id: Decimal | None = None


class ItemAdjustmentLineDetail_(QboModel):
    """ItemAdjustmentLineDetail."""

    QtyDiff: Decimal | None = None
    ItemRef: ReferenceType_ | None = None


class ItemBasedExpenseLine_(QboModel):
    """ItemBasedExpenseLine."""

    LinkedTxn: list[LinkedTxn_] | None = None
    Description: str | None = None
    ItemBasedExpenseLineDetail: ItemBasedExpenseLineDetail_ | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    DetailType: LineDetailTypeEnum | None = None
    Id: str | None = None


class ItemBasedExpenseLineBill_(QboModel):
    """ItemBasedExpenseLineBill."""

    LinkedTxn: list[dict[str, Any]] | None = None
    Description: str | None = None
    ItemBasedExpenseLineDetail: ItemBasedExpenseLineDetail_ | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    DetailType: LineDetailTypeEnum | None = None
    Id: str | None = None


class ItemBasedExpenseLineDetail_(QboModel):
    """ItemBasedExpenseLineDetail."""

    TaxInclusiveAmt: Decimal | None = None
    ItemRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None
    PriceLevelRef: ReferenceType_ | None = None
    ClassRef: ReferenceType_ | None = None
    TaxCodeRef: ReferenceType_ | None = None
    MarkupInfo: MarkupInfo_ | None = None
    BillableStatus: BillableStatusEnum | None = None
    Qty: Decimal | None = None
    UnitPrice: Decimal | None = None


class JournalEntry_(QboModel):
    """JournalEntry."""

    DocNumber: str | None = None
    SyncToken: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    TxnDate: date | None = None
    TotalAmt: Decimal | None = None
    ExchangeRate: Decimal | None = None
    CurrencyRef: CurrencyRef_ | None = None
    TaxRateRef: ReferenceType_ | None = None
    HomeTotalAmt: Decimal | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    Adjustment: bool | None = None
    Id: str | None = None
    Line: list[DescriptionOnlyLine_ | JournalEntryLine_] | None = None
    MetaData: ModificationMetadata_ | None = None


class JournalEntryLine_(QboModel):
    """JournalEntryLine."""

    Description: str | None = None
    JournalEntryLineDetail: JournalEntryLineDetail_ | None = None
    DetailType: LineDetailTypeEnum | None = None
    ProjectRef: ReferenceType_ | None = None
    CustomExtensions: CustomExtensions_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    Id: str | None = None


class JournalEntryLineDetail_(QboModel):
    """JournalEntryLineDetail."""

    TaxAmount: Decimal | None = None
    TaxInclusiveAmt: Decimal | None = None
    ClassRef: ReferenceType_ | None = None
    DepartmentRef: ReferenceType_ | None = None
    TaxCodeRef: ReferenceType_ | None = None
    BillableStatus: BillableStatusEnum | None = None
    TaxApplicableOn: TaxApplicableOnEnum | None = None
    PostingType: PostingTypeEnum | None = None
    AccountRef: ReferenceType_ | None = None
    Entity: Entity_ | None = None


class LineLinkedTxn_(QboModel):
    """LineLinkedTxn."""

    Amount: Decimal | None = None
    LinkedTxn: list[LinkedTxn_] | None = None


class LinkedTxn_(QboModel):
    """LinkedTxn."""

    TxnLineId: str | None = None
    TxnId: str | None = None
    TxnType: str | None = None


class MarkupInfo_(QboModel):
    """MarkupInfo."""

    PriceLevelRef: ReferenceType_ | None = None
    Percent: Decimal | None = None
    MarkUpIncomeAccountRef: ReferenceType_ | None = None


class MemoRef_(QboModel):
    """MemoRef."""

    value: str | None = None


class ModificationMetadata_(QboModel):
    """ModificationMetadata."""

    CreateTime: datetime | None = None
    LastUpdatedTime: datetime | None = None


class Payment_(QboModel):
    """Payment."""

    SyncToken: str | None = None
    PrivateNote: str | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    UnappliedAmt: Decimal | None = None
    DepositToAccountRef: ReferenceType_ | None = None
    CurrencyRef: CurrencyRef_ | None = None
    TotalAmt: Decimal | None = None
    ExchangeRate: Decimal | None = None
    Line: list[LineLinkedTxn_] | None = None
    ProjectRef: ReferenceType_ | None = None
    TxnSource: str | None = None
    PaymentRefNum: str | None = None
    TxnDate: date | None = None
    CreditCardPayment: CreditCardPaymentDetail_ | None = None
    TaxExemptionRef: ReferenceType_ | None = None
    CustomerRef: ReferenceType_ | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class PaymentMethod_(QboModel):
    """PaymentMethod."""

    SyncToken: str | None = None
    Name: str | None = None
    Active: bool | None = None
    Type: str | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class PhysicalAddress_(QboModel):
    """PhysicalAddress."""

    City: str | None = None
    Country: str | None = None
    Line5: str | None = None
    Line4: str | None = None
    Line3: str | None = None
    Line2: str | None = None
    Line1: str | None = None
    PostalCode: str | None = None
    CountrySubDivisionCode: str | None = None
    Id: str | None = None


class Preferences_(QboModel):
    """Preferences."""

    EmailMessagesPrefs: EmailMessagesPrefs_ | None = None
    SyncToken: str | None = None
    ProductAndServicesPrefs: ProductAndServicesPrefs_ | None = None
    ReportPrefs: ReportPrefs_ | None = None
    AccountingInfoPrefs: AccountingInfoPrefs_ | None = None
    SalesFormsPrefs: SalesFormsPref_ | None = None
    VendorAndPurchasesPrefs: VendorAndPurchasePrefs_ | None = None
    TaxPrefs: TaxPrefs_ | None = None
    OtherPrefs: dict[str, Any] | None = None
    TimeTrackingPrefs: TimeTrackingPrefs_ | None = None
    CurrencyPrefs: CurrencyPrefs_ | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class ProductAndServicesPrefs_(QboModel):
    """ProductAndServicesPrefs."""

    RevenueRecognitionEnabled: bool | None = None
    RecognitionFrequencyType: str | None = None
    ForSales: bool | None = None
    QuantityOnHand: bool | None = None
    QuantityWithPriceAndRate: bool | None = None
    ForPurchase: bool | None = None


class Purchase_(QboModel):
    """Purchase."""

    TxnDate: date | None = None
    CurrencyRef: CurrencyRef_ | None = None
    PrintStatus: str | None = None
    RemitToAddr: PhysicalAddress_ | None = None
    TxnSource: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: list[AccountBasedExpenseLine_ | ItemBasedExpenseLine_] | None = None
    Credit: bool | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    PurchaseEx: dict[str, Any] | None = None
    ExchangeRate: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    PaymentType: str | None = None
    EntityRef: ReferenceType_ | None = None
    IncludeInAnnualTPAR: bool | None = None
    AccountRef: ReferenceType_ | None = None
    Id: str | None = None


class PurchaseOrder_(QboModel):
    """PurchaseOrder."""

    TxnDate: date | None = None
    CurrencyRef: CurrencyRef_ | None = None
    CustomField: CustomField_ | None = None
    APAccountRef: ReferenceType_ | None = None
    POEmail: EmailAddress_ | None = None
    ClassRef: ReferenceType_ | None = None
    SalesTermRef: ReferenceType_ | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    Memo: str | None = None
    POStatus: str | None = None
    DueDate: date | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    VendorRef: ReferenceType_ | None = None
    ShipMethodRef: ReferenceType_ | None = None
    RecurDataRef: ReferenceType_ | None = None
    Line: list[AccountBasedExpenseLine_ | ItemBasedExpenseLine_] | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    ShipTo: ReferenceType_ | None = None
    ExchangeRate: Decimal | None = None
    ShipAddr: PhysicalAddress_ | None = None
    VendorAddr: PhysicalAddress_ | None = None
    EmailStatus: str | None = None
    Id: str | None = None


class RecurringInfo_(QboModel):
    """RecurringInfo."""

    Active: bool | None = None
    RecurType: str | None = None
    ScheduleInfo: RecurringScheduleInfo_ | None = None
    Name: str | None = None


class RecurringScheduleInfo_(QboModel):
    """RecurringScheduleInfo."""

    DayOfWeek: str | None = None
    StartDate: datetime | None = None
    MaxOccurrences: str | None = None
    RemindDays: str | None = None
    IntervalType: str | None = None
    WeekOfMonth: str | None = None
    MonthOfYear: str | None = None
    DaysBefore: str | None = None
    NextDate: datetime | None = None
    NumInterval: str | None = None
    EndDate: datetime | None = None
    PreviousDate: datetime | None = None
    DayOfMonth: str | None = None


class RecurringTransaction_(QboModel):
    """RecurringTransaction."""

    SyncToken: str | None = None
    RecurringInfo: RecurringInfo_ | None = None
    RecurDataRef: ReferenceType_ | None = None
    Type: str | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class ReferenceType_(QboModel):
    """ReferenceType."""

    name: str | None = None
    value: str | None = None


class RefundReceipt_(QboModel):
    """RefundReceipt."""

    TxnDate: date | None = None
    CurrencyRef: CurrencyRef_ | None = None
    CustomField: CustomField_ | None = None
    HomeBalance: Decimal | None = None
    ClassRef: ReferenceType_ | None = None
    PrintStatus: str | None = None
    PaymentRefNum: str | None = None
    CheckPayment: CheckPayment_ | None = None
    TxnSource: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    MetaData: ModificationMetadata_ | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    DepositToAccountRef: ReferenceType_ | None = None
    Line: (
        list[
            DescriptionOnlyLine_
            | DiscountLine_
            | GroupLine_
            | SalesItemLine_
            | SubTotalLine_
        ]
        | None
    ) = None
    CustomerMemo: MemoRef_ | None = None
    ProjectRef: ReferenceType_ | None = None
    TaxExemptionRef: ReferenceType_ | None = None
    CreditCardPayment: CreditCardPaymentDetail_ | None = None
    Balance: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    ExchangeRate: Decimal | None = None
    ShipAddr: PhysicalAddress_ | None = None
    Id: str | None = None
    DepartmentRef: ReferenceType_ | None = None
    PaymentType: PaymentTypeEnum | None = None
    BillAddr: PhysicalAddress_ | None = None
    ApplyTaxAfterDiscount: bool | None = None
    BillEmail: EmailAddress_ | None = None
    HomeTotalAmt: Decimal | None = None


class ReimburseCharge_(QboModel):
    """ReimburseCharge."""

    SyncToken: str | None = None
    PrivateNote: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    HasBeenInvoiced: bool | None = None
    CurrencyRef: CurrencyRef_ | None = None
    ExchangeRate: Decimal | None = None
    Line: list[ReimburseChargeLine_] | None = None
    HomeTotalAmt: Decimal | None = None
    Amount: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class ReimburseChargeLine_(QboModel):
    """ReimburseChargeLine."""

    LinkedTxn: list[LinkedTxn_] | None = None
    LineNum: Decimal | None = None
    ReimburseLineDetail: DiscountLineDetail_ | None = None
    LineId: str | None = None
    DetailType: LineDetailTypeEnum | None = None


class ReportPrefs_(QboModel):
    """ReportPrefs."""

    ReportBasis: ReportBasisEnum | None = None
    CalcAgingReportFromTxnDate: bool | None = None


class SalesFormsPref_(QboModel):
    """SalesFormsPref."""

    SalesEmailBcc: EmailAddress_ | None = None
    AllowServiceDate: bool | None = None
    EstimateMessage: str | None = None
    EmailCopyToCompany: bool | None = None
    DefaultCustomerMessage: str | None = None
    AllowShipping: bool | None = None
    SalesEmailCc: EmailAddress_ | None = None
    DefaultDiscountAccount: bool | None = None
    IPNSupportEnabled: bool | None = None
    ETransactionPaymentEnabled: bool | None = None
    DefaultTerms: ReferenceType_ | None = None
    UsingProgressInvoicing: bool | None = None
    AllowDeposit: bool | None = None
    UsingPriceLevels: bool | None = None
    DefaultShippingAccount: bool | None = None
    ETransactionAttachPDF: bool | None = None
    CustomTxnNumbers: bool | None = None
    ETransactionEnabledStatus: dict[str, Any] | None = None
    AllowEstimates: bool | None = None
    AllowDiscount: bool | None = None
    CustomField: (CustomFieldBoolsales_ | CustomFieldStringsales_) | None = None
    AutoApplyCredit: bool | None = None


class SalesItemLine_(QboModel):
    """SalesItemLine."""

    Description: str | None = None
    DetailType: LineDetailTypeEnum | None = None
    SalesItemLineDetail: SalesItemLineDetail_ | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    CustomExtensions: CustomExtensions_ | None = None
    Id: str | None = None


class SalesItemLineDetail_(QboModel):
    """SalesItemLineDetail."""

    TaxInclusiveAmt: Decimal | None = None
    ItemRef: ReferenceType_ | None = None
    ClassRef: ReferenceType_ | None = None
    TaxCodeRef: ReferenceType_ | None = None
    MarkupInfo: MarkupInfo_ | None = None
    ItemAccountRef: ReferenceType_ | None = None
    ServiceDate: date | None = None
    Qty: Decimal | None = None
    UnitPrice: Decimal | None = None
    TaxClassificationRef: ReferenceType_ | None = None


class SalesReceipt_(QboModel):
    """SalesReceipt."""

    TxnDate: date | None = None
    ShipFromAddr: PhysicalAddress_ | None = None
    CurrencyRef: CurrencyRef_ | None = None
    CustomField: CustomField_ | None = None
    HomeBalance: Decimal | None = None
    ShipDate: date | None = None
    TrackingNum: str | None = None
    ClassRef: ReferenceType_ | None = None
    PrintStatus: str | None = None
    PaymentRefNum: str | None = None
    DeliveryInfo: DeliveryInfo_ | None = None
    TxnSource: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    RecurDataRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    ApplyTaxAfterDiscount: bool | None = None
    DocNumber: str | None = None
    PrivateNote: str | None = None
    DepositToAccountRef: ReferenceType_ | None = None
    Line: (
        list[
            DescriptionOnlyLine_
            | DiscountLine_
            | GroupLine_
            | SalesItemLine_
            | SubTotalLine_
        ]
        | None
    ) = None
    CustomerMemo: MemoRef_ | None = None
    EmailStatus: str | None = None
    ProjectRef: ReferenceType_ | None = None
    CreditCardPayment: CreditCardPaymentDetail_ | None = None
    Balance: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    TxnTaxDetail: TxnTaxDetail_ | None = None
    SyncToken: str | None = None
    PaymentMethodRef: ReferenceType_ | None = None
    ExchangeRate: Decimal | None = None
    ShipAddr: PhysicalAddress_ | None = None
    HomeTotalAmt: Decimal | None = None
    DepartmentRef: ReferenceType_ | None = None
    ShipMethodRef: ReferenceType_ | None = None
    BillAddr: PhysicalAddress_ | None = None
    FreeFormAddress: bool | None = None
    MetaData: ModificationMetadata_ | None = None
    BillEmail: EmailAddress_ | None = None
    Id: str | None = None


class SubTotalLine_(QboModel):
    """SubTotalLine."""

    Description: str | None = None
    SubTotalLineDetail: SubTotalLineDetail_ | None = None
    DetailType: LineDetailTypeEnum | None = None
    LineNum: Decimal | None = None
    Amount: Decimal | None = None
    Id: str | None = None


class SubTotalLineDetail_(QboModel):
    """SubTotalLineDetail."""

    ItemRef: ReferenceType_ | None = None


class TaxAgency_(QboModel):
    """TaxAgency."""

    SyncToken: str | None = None
    TaxAgencyConfig: str | None = None
    DisplayName: str | None = None
    TaxTrackedOnSales: bool | None = None
    TaxTrackedOnPurchases: bool | None = None
    LastFileDate: date | None = None
    Id: str | None = None
    TaxRegistrationNumber: str | None = None
    MetaData: ModificationMetadata_ | None = None


class TaxClassification_(QboModel):
    """TaxClassification."""

    ApplicableTo: ItemTypeEnum | None = None
    Code: str | None = None
    Name: str | None = None
    Level: str | None = None
    ParentRef: ReferenceType_ | None = None
    Description: str | None = None


class TaxCode_(QboModel):
    """TaxCode."""

    SyncToken: str | None = None
    TaxGroup: bool | None = None
    PurchaseTaxRateList: TaxRateList_ | None = None
    TaxCodeConfigType: str | None = None
    Taxable: bool | None = None
    Name: str | None = None
    Active: bool | None = None
    Description: str | None = None
    Hidden: bool | None = None
    MetaData: ModificationMetadata_ | None = None
    Id: str | None = None
    SalesTaxRateList: TaxRateList_ | None = None


class TaxLine_(QboModel):
    """TaxLine."""

    DetailType: LineDetailTypeEnum | None = None
    Amount: Decimal | None = None
    TaxLineDetail: TaxLineDetail_ | None = None


class TaxLineDetail_(QboModel):
    """TaxLineDetail."""

    NetAmountTaxable: Decimal | None = None
    PercentBased: bool | None = None
    TaxInclusiveAmount: Decimal | None = None
    OverrideDeltaAmount: Decimal | None = None
    TaxRateRef: ReferenceType_ | None = None
    TaxPercent: Decimal | None = None


class TaxPayment_(QboModel):
    """TaxPayment."""

    Refund: bool | None = None
    TxnDate: date | None = None
    PaymentAccountRef: ReferenceType_ | None = None
    Description: str | None = None
    SyncToken: str | None = None
    PaymentAmount: Decimal | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class TaxPrefs_(QboModel):
    """TaxPrefs."""

    PartnerTaxEnabled: bool | None = None
    TaxGroupCodeRef: str | None = None
    UsingSalesTax: bool | None = None


class TaxRate_(QboModel):
    """TaxRate."""

    RateValue: Decimal | None = None
    SyncToken: str | None = None
    Name: str | None = None
    AgencyRef: ReferenceType_ | None = None
    SpecialTaxType: str | None = None
    EffectiveTaxRate: EffectiveTaxRatedata_ | None = None
    DisplayType: str | None = None
    TaxReturnLineRef: ReferenceType_ | None = None
    Active: bool | None = None
    MetaData: ModificationMetadata_ | None = None
    Id: str | None = None
    OriginalTaxRate: str | None = None
    Description: str | None = None


class TaxRateDetail_(QboModel):
    """TaxRateDetail."""

    TaxTypeApplicable: str | None = None
    TaxRateRef: ReferenceType_ | None = None
    TaxOrder: int | None = None


class TaxRateDetails_(QboModel):
    """TaxRateDetails."""

    RateValue: dict[str, Any] | None = None
    TaxRateId: str | None = None
    TaxApplicableOn: TaxApplicableOnEnum | None = None
    TaxAgencyId: dict[str, Any] | None = None
    TaxRateName: str | None = None


class TaxRateList_(QboModel):
    """TaxRateList."""

    TaxRateDetail: list[TaxRateDetail_] | None = None


class TaxService_(QboModel):
    """TaxService."""

    TaxCodeId: str | None = None
    TaxCode: str | None = None
    TaxRateDetails: list[TaxRateDetails_] | None = None


class TelephoneNumber_(QboModel):
    """TelephoneNumber."""

    FreeFormNumber: str | None = None


class TelephoneNumber30_(QboModel):
    """TelephoneNumber30."""

    FreeFormNumber: str | None = None


class Term_(QboModel):
    """Term."""

    SyncToken: str | None = None
    DayOfMonthDue: int | None = None
    Name: str | None = None
    DiscountDayOfMonth: dict[str, Any] | None = None
    DiscountPercent: Decimal | None = None
    DiscountDays: int | None = None
    DueNextMonthDays: dict[str, Any] | None = None
    DueDays: int | None = None
    Active: bool | None = None
    Type: str | None = None
    Id: str | None = None
    MetaData: ModificationMetadata_ | None = None


class Threshold_(QboModel):
    """Threshold."""

    currentCount: str | None = None
    aboveThreshold: str | None = None
    enforced: str | None = None
    limit: str | None = None
    name: str | None = None


class TimeActivity_(QboModel):
    """TimeActivity."""

    TxnDate: date | None = None
    NameOf: str | None = None
    ClassRef: ReferenceType_ | None = None
    EndTime: datetime | None = None
    Description: str | None = None
    Hours: int | None = None
    Taxable: bool | None = None
    MetaData: ModificationMetadata_ | None = None
    VendorRef: ReferenceType_ | None = None
    CostRate: Decimal | None = None
    ItemRef: ReferenceType_ | None = None
    ProjectRef: ReferenceType_ | None = None
    PayrollItemRef: ReferenceType_ | None = None
    BillableStatus: BillableStatusEnum | None = None
    HourlyRate: Decimal | None = None
    CustomerRef: ReferenceType_ | None = None
    SyncToken: str | None = None
    EmployeeRef: ReferenceType_ | None = None
    DepartmentRef: ReferenceType_ | None = None
    StartTime: datetime | None = None
    Id: str | None = None


class TimeTrackingPrefs_(QboModel):
    """TimeTrackingPrefs."""

    WorkWeekStartDate: WeekEnum | None = None
    MarkTimeEntriesBillable: bool | None = None
    ShowBillRateToAll: bool | None = None
    UsingSalesTax: bool | None = None
    BillCustomers: bool | None = None


class Transfer_(QboModel):
    """Transfer."""

    SyncToken: str | None = None
    PrivateNote: str | None = None
    RecurDataRef: ReferenceType_ | None = None
    TxnDate: date | None = None
    ToAccountRef: ReferenceType_ | None = None
    Amount: Decimal | None = None
    Id: str | None = None
    FromAccountRef: ReferenceType_ | None = None
    MetaData: ModificationMetadata_ | None = None


class TxnTaxDetail_(QboModel):
    """TxnTaxDetail."""

    TxnTaxCodeRef: ReferenceType_ | None = None
    TotalTax: Decimal | None = None
    TaxLine: list[TaxLine_] | None = None


class Vendor_(QboModel):
    """Vendor."""

    PrimaryEmailAddr: EmailAddress_ | None = None
    DisplayName: str | None = None
    OtherContactInfo: ContactInfo_ | None = None
    Title: str | None = None
    TermRef: ReferenceType_ | None = None
    Source: str | None = None
    GivenName: str | None = None
    T4AEligible: bool | None = None
    Fax: TelephoneNumber30_ | None = None
    CurrencyRef: CurrencyRef_ | None = None
    Mobile: TelephoneNumber30_ | None = None
    PrimaryPhone: TelephoneNumber30_ | None = None
    Active: bool | None = None
    AlternatePhone: TelephoneNumber30_ | None = None
    MetaData: ModificationMetadata_ | None = None
    Vendor1099: bool | None = None
    CostRate: Decimal | None = None
    MiddleName: str | None = None
    BillRate: Decimal | None = None
    WebAddr: WebsiteAddress_ | None = None
    T5018Eligible: bool | None = None
    Balance: Decimal | None = None
    SyncToken: str | None = None
    Suffix: str | None = None
    CompanyName: str | None = None
    FamilyName: str | None = None
    VendorPaymentBankDetail: VendorPaymentBankDetail_ | None = None
    TaxIdentifier: str | None = None
    AcctNum: str | None = None
    HasTPAR: bool | None = None
    PrintOnCheckName: str | None = None
    BillAddr: PhysicalAddress_ | None = None
    Id: str | None = None


class VendorAndPurchasePrefs_(QboModel):
    """VendorAndPurchasePrefs."""

    DefaultMarkupAccount: ReferenceType_ | None = None
    TrackingByCustomer: bool | None = None
    POCustomField: (CustomFieldBoolpo_ | CustomFieldStringpo_) | None = None
    DefaultTerms: ReferenceType_ | None = None
    BillableExpenseTracking: bool | None = None
    DefaultMarkup: Decimal | None = None
    TPAREnabled: bool | None = None


class VendorCredit_(QboModel):
    """VendorCredit."""

    DocNumber: str | None = None
    SyncToken: str | None = None
    PrivateNote: str | None = None
    LinkedTxn: list[LinkedTxn_] | None = None
    VendorRef: ReferenceType_ | None = None
    RecurDataRef: ReferenceType_ | None = None
    GlobalTaxCalculation: GlobalTaxCalculationEnum | None = None
    TotalAmt: Decimal | None = None
    ExchangeRate: Decimal | None = None
    APAccountRef: ReferenceType_ | None = None
    DepartmentRef: ReferenceType_ | None = None
    TxnDate: date | None = None
    IncludeInAnnualTPAR: bool | None = None
    Line: list[AccountBasedExpenseLine_ | ItemBasedExpenseLine_] | None = None
    Balance: Decimal | None = None
    Id: str | None = None
    CurrencyRef: CurrencyRef_ | None = None
    MetaData: ModificationMetadata_ | None = None


class VendorPaymentBankDetail_(QboModel):
    """VendorPaymentBankDetail."""

    BankAccountName: str | None = None
    BankBranchIdentifier: str | None = None
    BankAccountNumber: str | None = None
    StatementText: str | None = None


class WebsiteAddress_(QboModel):
    """WebsiteAddress."""

    URI: str | None = None


# Public aliases. Classes are defined with a trailing underscore so
# that a field named after its own type cannot shadow it; these are
# the names callers use.
Account_.__name__ = "Account"
Account_.__qualname__ = "Account"
Account = Account_
AccountBasedExpenseLine_.__name__ = "AccountBasedExpenseLine"
AccountBasedExpenseLine_.__qualname__ = "AccountBasedExpenseLine"
AccountBasedExpenseLine = AccountBasedExpenseLine_
AccountBasedExpenseLineBill_.__name__ = "AccountBasedExpenseLineBill"
AccountBasedExpenseLineBill_.__qualname__ = "AccountBasedExpenseLineBill"
AccountBasedExpenseLineBill = AccountBasedExpenseLineBill_
AccountBasedExpenseLineDetail_.__name__ = "AccountBasedExpenseLineDetail"
AccountBasedExpenseLineDetail_.__qualname__ = "AccountBasedExpenseLineDetail"
AccountBasedExpenseLineDetail = AccountBasedExpenseLineDetail_
AccountingInfoPrefs_.__name__ = "AccountingInfoPrefs"
AccountingInfoPrefs_.__qualname__ = "AccountingInfoPrefs"
AccountingInfoPrefs = AccountingInfoPrefs_
AssociatedValues_.__name__ = "AssociatedValues"
AssociatedValues_.__qualname__ = "AssociatedValues"
AssociatedValues = AssociatedValues_
Attachable_.__name__ = "Attachable"
Attachable_.__qualname__ = "Attachable"
Attachable = Attachable_
AttachableRef_.__name__ = "AttachableRef"
AttachableRef_.__qualname__ = "AttachableRef"
AttachableRef = AttachableRef_
Bill_.__name__ = "Bill"
Bill_.__qualname__ = "Bill"
Bill = Bill_
BillPayment_.__name__ = "BillPayment"
BillPayment_.__qualname__ = "BillPayment"
BillPayment = BillPayment_
BillPaymentCheck_.__name__ = "BillPaymentCheck"
BillPaymentCheck_.__qualname__ = "BillPaymentCheck"
BillPaymentCheck = BillPaymentCheck_
BillPaymentCreditCard_.__name__ = "BillPaymentCreditCard"
BillPaymentCreditCard_.__qualname__ = "BillPaymentCreditCard"
BillPaymentCreditCard = BillPaymentCreditCard_
Budget_.__name__ = "Budget"
Budget_.__qualname__ = "Budget"
Budget = Budget_
BudgetDetail_.__name__ = "BudgetDetail"
BudgetDetail_.__qualname__ = "BudgetDetail"
BudgetDetail = BudgetDetail_
CashbackInfo_.__name__ = "CashbackInfo"
CashbackInfo_.__qualname__ = "CashbackInfo"
CashbackInfo = CashbackInfo_
ChangeOrder_.__name__ = "ChangeOrder"
ChangeOrder_.__qualname__ = "ChangeOrder"
ChangeOrder = ChangeOrder_
CheckPayment_.__name__ = "CheckPayment"
CheckPayment_.__qualname__ = "CheckPayment"
CheckPayment = CheckPayment_
Class_.__name__ = "Class"
Class_.__qualname__ = "Class"
Class = Class_
CompanyCurrency_.__name__ = "CompanyCurrency"
CompanyCurrency_.__qualname__ = "CompanyCurrency"
CompanyCurrency = CompanyCurrency_
CompanyInfo_.__name__ = "CompanyInfo"
CompanyInfo_.__qualname__ = "CompanyInfo"
CompanyInfo = CompanyInfo_
ContactInfo_.__name__ = "ContactInfo"
ContactInfo_.__qualname__ = "ContactInfo"
ContactInfo = ContactInfo_
CreditCardPayment_.__name__ = "CreditCardPayment"
CreditCardPayment_.__qualname__ = "CreditCardPayment"
CreditCardPayment = CreditCardPayment_
CreditCardPaymentDetail_.__name__ = "CreditCardPaymentDetail"
CreditCardPaymentDetail_.__qualname__ = "CreditCardPaymentDetail"
CreditCardPaymentDetail = CreditCardPaymentDetail_
CreditChargeInfo_.__name__ = "CreditChargeInfo"
CreditChargeInfo_.__qualname__ = "CreditChargeInfo"
CreditChargeInfo = CreditChargeInfo_
CreditChargeResponse_.__name__ = "CreditChargeResponse"
CreditChargeResponse_.__qualname__ = "CreditChargeResponse"
CreditChargeResponse = CreditChargeResponse_
CreditMemo_.__name__ = "CreditMemo"
CreditMemo_.__qualname__ = "CreditMemo"
CreditMemo = CreditMemo_
CurrencyPrefs_.__name__ = "CurrencyPrefs"
CurrencyPrefs_.__qualname__ = "CurrencyPrefs"
CurrencyPrefs = CurrencyPrefs_
CurrencyRef_.__name__ = "CurrencyRef"
CurrencyRef_.__qualname__ = "CurrencyRef"
CurrencyRef = CurrencyRef_
CustomExtensions_.__name__ = "CustomExtensions"
CustomExtensions_.__qualname__ = "CustomExtensions"
CustomExtensions = CustomExtensions_
CustomField_.__name__ = "CustomField"
CustomField_.__qualname__ = "CustomField"
CustomField = CustomField_
CustomFieldBoolpo_.__name__ = "CustomFieldBoolpo"
CustomFieldBoolpo_.__qualname__ = "CustomFieldBoolpo"
CustomFieldBoolpo = CustomFieldBoolpo_
CustomFieldBoolsales_.__name__ = "CustomFieldBoolsales"
CustomFieldBoolsales_.__qualname__ = "CustomFieldBoolsales"
CustomFieldBoolsales = CustomFieldBoolsales_
CustomFieldStringpo_.__name__ = "CustomFieldStringpo"
CustomFieldStringpo_.__qualname__ = "CustomFieldStringpo"
CustomFieldStringpo = CustomFieldStringpo_
CustomFieldStringsales_.__name__ = "CustomFieldStringsales"
CustomFieldStringsales_.__qualname__ = "CustomFieldStringsales"
CustomFieldStringsales = CustomFieldStringsales_
Customer_.__name__ = "Customer"
Customer_.__qualname__ = "Customer"
Customer = Customer_
CustomerType_.__name__ = "CustomerType"
CustomerType_.__qualname__ = "CustomerType"
CustomerType = CustomerType_
CustomerTypeRef_.__name__ = "CustomerTypeRef"
CustomerTypeRef_.__qualname__ = "CustomerTypeRef"
CustomerTypeRef = CustomerTypeRef_
DeliveryInfo_.__name__ = "DeliveryInfo"
DeliveryInfo_.__qualname__ = "DeliveryInfo"
DeliveryInfo = DeliveryInfo_
Department_.__name__ = "Department"
Department_.__qualname__ = "Department"
Department = Department_
Deposit_.__name__ = "Deposit"
Deposit_.__qualname__ = "Deposit"
Deposit = Deposit_
DepositLine_.__name__ = "DepositLine"
DepositLine_.__qualname__ = "DepositLine"
DepositLine = DepositLine_
DepositLineDetail_.__name__ = "DepositLineDetail"
DepositLineDetail_.__qualname__ = "DepositLineDetail"
DepositLineDetail = DepositLineDetail_
DescriptionOnly_.__name__ = "DescriptionOnly"
DescriptionOnly_.__qualname__ = "DescriptionOnly"
DescriptionOnly = DescriptionOnly_
DescriptionOnlyLine_.__name__ = "DescriptionOnlyLine"
DescriptionOnlyLine_.__qualname__ = "DescriptionOnlyLine"
DescriptionOnlyLine = DescriptionOnlyLine_
DiscountLine_.__name__ = "DiscountLine"
DiscountLine_.__qualname__ = "DiscountLine"
DiscountLine = DiscountLine_
DiscountLineDetail_.__name__ = "DiscountLineDetail"
DiscountLineDetail_.__qualname__ = "DiscountLineDetail"
DiscountLineDetail = DiscountLineDetail_
EffectiveTaxRatedata_.__name__ = "EffectiveTaxRatedata"
EffectiveTaxRatedata_.__qualname__ = "EffectiveTaxRatedata"
EffectiveTaxRatedata = EffectiveTaxRatedata_
EmailAddress_.__name__ = "EmailAddress"
EmailAddress_.__qualname__ = "EmailAddress"
EmailAddress = EmailAddress_
EmailMessageType_.__name__ = "EmailMessageType"
EmailMessageType_.__qualname__ = "EmailMessageType"
EmailMessageType = EmailMessageType_
EmailMessagesPrefs_.__name__ = "EmailMessagesPrefs"
EmailMessagesPrefs_.__qualname__ = "EmailMessagesPrefs"
EmailMessagesPrefs = EmailMessagesPrefs_
Employee_.__name__ = "Employee"
Employee_.__qualname__ = "Employee"
Employee = Employee_
Entitlements_.__name__ = "Entitlements"
Entitlements_.__qualname__ = "Entitlements"
Entitlements = Entitlements_
Entity_.__name__ = "Entity"
Entity_.__qualname__ = "Entity"
Entity = Entity_
Estimate_.__name__ = "Estimate"
Estimate_.__qualname__ = "Estimate"
Estimate = Estimate_
Exchangerate_.__name__ = "Exchangerate"
Exchangerate_.__qualname__ = "Exchangerate"
Exchangerate = Exchangerate_
GroupLine_.__name__ = "GroupLine"
GroupLine_.__qualname__ = "GroupLine"
GroupLine = GroupLine_
GroupLineDetail_.__name__ = "GroupLineDetail"
GroupLineDetail_.__qualname__ = "GroupLineDetail"
GroupLineDetail = GroupLineDetail_
InventoryAdjustment_.__name__ = "InventoryAdjustment"
InventoryAdjustment_.__qualname__ = "InventoryAdjustment"
InventoryAdjustment = InventoryAdjustment_
Invoice_.__name__ = "Invoice"
Invoice_.__qualname__ = "Invoice"
Invoice = Invoice_
Item_.__name__ = "Item"
Item_.__qualname__ = "Item"
Item = Item_
ItemAdjustmentLine_.__name__ = "ItemAdjustmentLine"
ItemAdjustmentLine_.__qualname__ = "ItemAdjustmentLine"
ItemAdjustmentLine = ItemAdjustmentLine_
ItemAdjustmentLineDetail_.__name__ = "ItemAdjustmentLineDetail"
ItemAdjustmentLineDetail_.__qualname__ = "ItemAdjustmentLineDetail"
ItemAdjustmentLineDetail = ItemAdjustmentLineDetail_
ItemBasedExpenseLine_.__name__ = "ItemBasedExpenseLine"
ItemBasedExpenseLine_.__qualname__ = "ItemBasedExpenseLine"
ItemBasedExpenseLine = ItemBasedExpenseLine_
ItemBasedExpenseLineBill_.__name__ = "ItemBasedExpenseLineBill"
ItemBasedExpenseLineBill_.__qualname__ = "ItemBasedExpenseLineBill"
ItemBasedExpenseLineBill = ItemBasedExpenseLineBill_
ItemBasedExpenseLineDetail_.__name__ = "ItemBasedExpenseLineDetail"
ItemBasedExpenseLineDetail_.__qualname__ = "ItemBasedExpenseLineDetail"
ItemBasedExpenseLineDetail = ItemBasedExpenseLineDetail_
JournalEntry_.__name__ = "JournalEntry"
JournalEntry_.__qualname__ = "JournalEntry"
JournalEntry = JournalEntry_
JournalEntryLine_.__name__ = "JournalEntryLine"
JournalEntryLine_.__qualname__ = "JournalEntryLine"
JournalEntryLine = JournalEntryLine_
JournalEntryLineDetail_.__name__ = "JournalEntryLineDetail"
JournalEntryLineDetail_.__qualname__ = "JournalEntryLineDetail"
JournalEntryLineDetail = JournalEntryLineDetail_
LineLinkedTxn_.__name__ = "LineLinkedTxn"
LineLinkedTxn_.__qualname__ = "LineLinkedTxn"
LineLinkedTxn = LineLinkedTxn_
LinkedTxn_.__name__ = "LinkedTxn"
LinkedTxn_.__qualname__ = "LinkedTxn"
LinkedTxn = LinkedTxn_
MarkupInfo_.__name__ = "MarkupInfo"
MarkupInfo_.__qualname__ = "MarkupInfo"
MarkupInfo = MarkupInfo_
MemoRef_.__name__ = "MemoRef"
MemoRef_.__qualname__ = "MemoRef"
MemoRef = MemoRef_
ModificationMetadata_.__name__ = "ModificationMetadata"
ModificationMetadata_.__qualname__ = "ModificationMetadata"
ModificationMetadata = ModificationMetadata_
Payment_.__name__ = "Payment"
Payment_.__qualname__ = "Payment"
Payment = Payment_
PaymentMethod_.__name__ = "PaymentMethod"
PaymentMethod_.__qualname__ = "PaymentMethod"
PaymentMethod = PaymentMethod_
PhysicalAddress_.__name__ = "PhysicalAddress"
PhysicalAddress_.__qualname__ = "PhysicalAddress"
PhysicalAddress = PhysicalAddress_
Preferences_.__name__ = "Preferences"
Preferences_.__qualname__ = "Preferences"
Preferences = Preferences_
ProductAndServicesPrefs_.__name__ = "ProductAndServicesPrefs"
ProductAndServicesPrefs_.__qualname__ = "ProductAndServicesPrefs"
ProductAndServicesPrefs = ProductAndServicesPrefs_
Purchase_.__name__ = "Purchase"
Purchase_.__qualname__ = "Purchase"
Purchase = Purchase_
PurchaseOrder_.__name__ = "PurchaseOrder"
PurchaseOrder_.__qualname__ = "PurchaseOrder"
PurchaseOrder = PurchaseOrder_
RecurringInfo_.__name__ = "RecurringInfo"
RecurringInfo_.__qualname__ = "RecurringInfo"
RecurringInfo = RecurringInfo_
RecurringScheduleInfo_.__name__ = "RecurringScheduleInfo"
RecurringScheduleInfo_.__qualname__ = "RecurringScheduleInfo"
RecurringScheduleInfo = RecurringScheduleInfo_
RecurringTransaction_.__name__ = "RecurringTransaction"
RecurringTransaction_.__qualname__ = "RecurringTransaction"
RecurringTransaction = RecurringTransaction_
ReferenceType_.__name__ = "ReferenceType"
ReferenceType_.__qualname__ = "ReferenceType"
ReferenceType = ReferenceType_
RefundReceipt_.__name__ = "RefundReceipt"
RefundReceipt_.__qualname__ = "RefundReceipt"
RefundReceipt = RefundReceipt_
ReimburseCharge_.__name__ = "ReimburseCharge"
ReimburseCharge_.__qualname__ = "ReimburseCharge"
ReimburseCharge = ReimburseCharge_
ReimburseChargeLine_.__name__ = "ReimburseChargeLine"
ReimburseChargeLine_.__qualname__ = "ReimburseChargeLine"
ReimburseChargeLine = ReimburseChargeLine_
ReportPrefs_.__name__ = "ReportPrefs"
ReportPrefs_.__qualname__ = "ReportPrefs"
ReportPrefs = ReportPrefs_
SalesFormsPref_.__name__ = "SalesFormsPref"
SalesFormsPref_.__qualname__ = "SalesFormsPref"
SalesFormsPref = SalesFormsPref_
SalesItemLine_.__name__ = "SalesItemLine"
SalesItemLine_.__qualname__ = "SalesItemLine"
SalesItemLine = SalesItemLine_
SalesItemLineDetail_.__name__ = "SalesItemLineDetail"
SalesItemLineDetail_.__qualname__ = "SalesItemLineDetail"
SalesItemLineDetail = SalesItemLineDetail_
SalesReceipt_.__name__ = "SalesReceipt"
SalesReceipt_.__qualname__ = "SalesReceipt"
SalesReceipt = SalesReceipt_
SubTotalLine_.__name__ = "SubTotalLine"
SubTotalLine_.__qualname__ = "SubTotalLine"
SubTotalLine = SubTotalLine_
SubTotalLineDetail_.__name__ = "SubTotalLineDetail"
SubTotalLineDetail_.__qualname__ = "SubTotalLineDetail"
SubTotalLineDetail = SubTotalLineDetail_
TaxAgency_.__name__ = "TaxAgency"
TaxAgency_.__qualname__ = "TaxAgency"
TaxAgency = TaxAgency_
TaxClassification_.__name__ = "TaxClassification"
TaxClassification_.__qualname__ = "TaxClassification"
TaxClassification = TaxClassification_
TaxCode_.__name__ = "TaxCode"
TaxCode_.__qualname__ = "TaxCode"
TaxCode = TaxCode_
TaxLine_.__name__ = "TaxLine"
TaxLine_.__qualname__ = "TaxLine"
TaxLine = TaxLine_
TaxLineDetail_.__name__ = "TaxLineDetail"
TaxLineDetail_.__qualname__ = "TaxLineDetail"
TaxLineDetail = TaxLineDetail_
TaxPayment_.__name__ = "TaxPayment"
TaxPayment_.__qualname__ = "TaxPayment"
TaxPayment = TaxPayment_
TaxPrefs_.__name__ = "TaxPrefs"
TaxPrefs_.__qualname__ = "TaxPrefs"
TaxPrefs = TaxPrefs_
TaxRate_.__name__ = "TaxRate"
TaxRate_.__qualname__ = "TaxRate"
TaxRate = TaxRate_
TaxRateDetail_.__name__ = "TaxRateDetail"
TaxRateDetail_.__qualname__ = "TaxRateDetail"
TaxRateDetail = TaxRateDetail_
TaxRateDetails_.__name__ = "TaxRateDetails"
TaxRateDetails_.__qualname__ = "TaxRateDetails"
TaxRateDetails = TaxRateDetails_
TaxRateList_.__name__ = "TaxRateList"
TaxRateList_.__qualname__ = "TaxRateList"
TaxRateList = TaxRateList_
TaxService_.__name__ = "TaxService"
TaxService_.__qualname__ = "TaxService"
TaxService = TaxService_
TelephoneNumber_.__name__ = "TelephoneNumber"
TelephoneNumber_.__qualname__ = "TelephoneNumber"
TelephoneNumber = TelephoneNumber_
TelephoneNumber30_.__name__ = "TelephoneNumber30"
TelephoneNumber30_.__qualname__ = "TelephoneNumber30"
TelephoneNumber30 = TelephoneNumber30_
Term_.__name__ = "Term"
Term_.__qualname__ = "Term"
Term = Term_
Threshold_.__name__ = "Threshold"
Threshold_.__qualname__ = "Threshold"
Threshold = Threshold_
TimeActivity_.__name__ = "TimeActivity"
TimeActivity_.__qualname__ = "TimeActivity"
TimeActivity = TimeActivity_
TimeTrackingPrefs_.__name__ = "TimeTrackingPrefs"
TimeTrackingPrefs_.__qualname__ = "TimeTrackingPrefs"
TimeTrackingPrefs = TimeTrackingPrefs_
Transfer_.__name__ = "Transfer"
Transfer_.__qualname__ = "Transfer"
Transfer = Transfer_
TxnTaxDetail_.__name__ = "TxnTaxDetail"
TxnTaxDetail_.__qualname__ = "TxnTaxDetail"
TxnTaxDetail = TxnTaxDetail_
Vendor_.__name__ = "Vendor"
Vendor_.__qualname__ = "Vendor"
Vendor = Vendor_
VendorAndPurchasePrefs_.__name__ = "VendorAndPurchasePrefs"
VendorAndPurchasePrefs_.__qualname__ = "VendorAndPurchasePrefs"
VendorAndPurchasePrefs = VendorAndPurchasePrefs_
VendorCredit_.__name__ = "VendorCredit"
VendorCredit_.__qualname__ = "VendorCredit"
VendorCredit = VendorCredit_
VendorPaymentBankDetail_.__name__ = "VendorPaymentBankDetail"
VendorPaymentBankDetail_.__qualname__ = "VendorPaymentBankDetail"
VendorPaymentBankDetail = VendorPaymentBankDetail_
WebsiteAddress_.__name__ = "WebsiteAddress"
WebsiteAddress_.__qualname__ = "WebsiteAddress"
WebsiteAddress = WebsiteAddress_

#: Documented entity name -> its response model.
ENTITY_MODELS: dict[str, type[QboModel]] = {
    "Account": Account,
    "Attachable": Attachable,
    "Bill": Bill,
    "BillPayment": BillPayment,
    "Budget": Budget,
    "ChangeOrder": ChangeOrder,
    "Class": Class,
    "CompanyCurrency": CompanyCurrency,
    "CompanyInfo": CompanyInfo,
    "CreditCardPayment": CreditCardPayment,
    "CreditMemo": CreditMemo,
    "Customer": Customer,
    "CustomerType": CustomerType,
    "Department": Department,
    "Deposit": Deposit,
    "Employee": Employee,
    "Entitlements": Entitlements,
    "Estimate": Estimate,
    "Exchangerate": Exchangerate,
    "InventoryAdjustment": InventoryAdjustment,
    "Invoice": Invoice,
    "Item": Item,
    "JournalEntry": JournalEntry,
    "Payment": Payment,
    "PaymentMethod": PaymentMethod,
    "Preferences": Preferences,
    "Purchase": Purchase,
    "PurchaseOrder": PurchaseOrder,
    "RecurringTransaction": RecurringTransaction,
    "RefundReceipt": RefundReceipt,
    "ReimburseCharge": ReimburseCharge,
    "SalesReceipt": SalesReceipt,
    "TaxAgency": TaxAgency,
    "TaxClassification": TaxClassification,
    "TaxCode": TaxCode,
    "TaxPayment": TaxPayment,
    "TaxRate": TaxRate,
    "TaxService": TaxService,
    "Term": Term,
    "TimeActivity": TimeActivity,
    "Transfer": Transfer,
    "Vendor": Vendor,
    "VendorCredit": VendorCredit,
}

__all__ = [
    "QboModel",
    "ENTITY_MODELS",
    "AccountTypeEnum",
    "BillPaymentTypeEnum",
    "BillableStatusEnum",
    "BudgetEntryTypeEnum",
    "BudgetTypeEnum",
    "CCPaymentStatusEnum",
    "CustomFieldTypeEnum",
    "DeliveryTypeEnum",
    "EntityTypeEnum",
    "GlobalTaxCalculationEnum",
    "ItemTypeEnum",
    "LineDetailTypeEnum",
    "MonthEnum",
    "PaymentTypeEnum",
    "PostingTypeEnum",
    "PrintStatusEnum",
    "ReportBasisEnum",
    "TaxApplicableOnEnum",
    "TxnTypeEnum",
    "WeekEnum",
    "Account",
    "AccountBasedExpenseLine",
    "AccountBasedExpenseLineBill",
    "AccountBasedExpenseLineDetail",
    "AccountingInfoPrefs",
    "AssociatedValues",
    "Attachable",
    "AttachableRef",
    "Bill",
    "BillPayment",
    "BillPaymentCheck",
    "BillPaymentCreditCard",
    "Budget",
    "BudgetDetail",
    "CashbackInfo",
    "ChangeOrder",
    "CheckPayment",
    "Class",
    "CompanyCurrency",
    "CompanyInfo",
    "ContactInfo",
    "CreditCardPayment",
    "CreditCardPaymentDetail",
    "CreditChargeInfo",
    "CreditChargeResponse",
    "CreditMemo",
    "CurrencyPrefs",
    "CurrencyRef",
    "CustomExtensions",
    "CustomField",
    "CustomFieldBoolpo",
    "CustomFieldBoolsales",
    "CustomFieldStringpo",
    "CustomFieldStringsales",
    "Customer",
    "CustomerType",
    "CustomerTypeRef",
    "DeliveryInfo",
    "Department",
    "Deposit",
    "DepositLine",
    "DepositLineDetail",
    "DescriptionOnly",
    "DescriptionOnlyLine",
    "DiscountLine",
    "DiscountLineDetail",
    "EffectiveTaxRatedata",
    "EmailAddress",
    "EmailMessageType",
    "EmailMessagesPrefs",
    "Employee",
    "Entitlements",
    "Entity",
    "Estimate",
    "Exchangerate",
    "GroupLine",
    "GroupLineDetail",
    "InventoryAdjustment",
    "Invoice",
    "Item",
    "ItemAdjustmentLine",
    "ItemAdjustmentLineDetail",
    "ItemBasedExpenseLine",
    "ItemBasedExpenseLineBill",
    "ItemBasedExpenseLineDetail",
    "JournalEntry",
    "JournalEntryLine",
    "JournalEntryLineDetail",
    "LineLinkedTxn",
    "LinkedTxn",
    "MarkupInfo",
    "MemoRef",
    "ModificationMetadata",
    "Payment",
    "PaymentMethod",
    "PhysicalAddress",
    "Preferences",
    "ProductAndServicesPrefs",
    "Purchase",
    "PurchaseOrder",
    "RecurringInfo",
    "RecurringScheduleInfo",
    "RecurringTransaction",
    "ReferenceType",
    "RefundReceipt",
    "ReimburseCharge",
    "ReimburseChargeLine",
    "ReportPrefs",
    "SalesFormsPref",
    "SalesItemLine",
    "SalesItemLineDetail",
    "SalesReceipt",
    "SubTotalLine",
    "SubTotalLineDetail",
    "TaxAgency",
    "TaxClassification",
    "TaxCode",
    "TaxLine",
    "TaxLineDetail",
    "TaxPayment",
    "TaxPrefs",
    "TaxRate",
    "TaxRateDetail",
    "TaxRateDetails",
    "TaxRateList",
    "TaxService",
    "TelephoneNumber",
    "TelephoneNumber30",
    "Term",
    "Threshold",
    "TimeActivity",
    "TimeTrackingPrefs",
    "Transfer",
    "TxnTaxDetail",
    "Vendor",
    "VendorAndPurchasePrefs",
    "VendorCredit",
    "VendorPaymentBankDetail",
    "WebsiteAddress",
]
